ec-europa/platform-dev

composer.json
composer.lock

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-5415

NEXTEUROPA-5415

---

profiles/drupal-org.make

security update SA-CONTRIB-2015-139

NEXTEUROPA-5338: update workbench_email to v 3.4

---

profiles/multisite_drupal_standard/nexteuropa.make

NEXTEUROPA-5365: update smart trom to 1.5

---

sites/all/modules/custom/ecas/ecas_import_users/ecas_import_users.info
sites/all/modules/custom/ecas/ecas_import_users/ecas_import_users.install
sites/all/modules/custom/ecas/ecas_import_users/ecas_import_users.module
sites/all/modules/custom/ecas/ecas_import_users/ecas_import_users.test

https://webgate.ec.europa.eu/CITnet/jira/browse/MULTISITE-5080

MULTISITE-5080 Apply the mentioned patch and cleaned up the source.

---

resources/multisite_drupal_standard.make

I tested with the following link: http://dai.ly/x4gfqu

MULTISITE-7082-dailymotion-short-url

---

sites/all/modules/features/custom/splash_screen/splash_screen.module

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-5585

HOTFIX/NEXTEUROPA-5585: fix link language version

---

tests/src/Context/MinkContext.php

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-5653

NEXTEUROPA-5653 fix behat homepage functions

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.strongarm.inc
tests/features/menus/user_menu.feature

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-5771

NEXTEUROPA-5771 : Change frontpage

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.install
profiles/common/modules/features/multisite_settings/multisite_settings_core/multisite_settings_core.context.inc
tests/features/blocks_display.feature

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-5755

NEXTEUROPA-5755: Missing default header and footer block

---

phpcs-ruleset.xml
profiles/common/modules/features/social_bookmark/css/social_bookmark.form.css
profiles/common/modules/features/social_bookmark/scripts/form_script.js
profiles/common/modules/features/social_bookmark/scripts/social_bookmark.form.js
profiles/common/modules/features/social_bookmark/social_bookmark.admin.inc
profiles/common/modules/features/social_bookmark/social_bookmark.features.inc
profiles/common/modules/features/social_bookmark/social_bookmark.features.user_permission.inc
profiles/common/modules/features/social_bookmark/social_bookmark.install
profiles/common/modules/features/social_bookmark/social_bookmark.module
profiles/common/modules/features/social_bookmark/tests/social_bookmark.extra.test
profiles/common/modules/features/social_bookmark/tests/social_bookmark.test

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-5801

NEXTEUROPA-5801 : Fix coding standards in social_bookmark

---

sites/all/modules/custom/language_selector_page/language_selector_page.info
sites/all/modules/custom/language_selector_page/language_selector_page.module
sites/all/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.module
sites/all/modules/features/custom/nexteuropa_multilingual/nexteuropa_multilingual.module

language fallback = default languagage

NEXTEUROPA-5640: fix language fallback

---

build.package.xml

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-4958

NEXTEUROPA-4958: Install Composer dependencies automatically when building

---

phpcs-ruleset.xml
profiles/multisite_drupal_communities/modules/custom/multisite_drupal_access/multisite_drupal_access.info
profiles/multisite_drupal_communities/modules/custom/multisite_drupal_access/multisite_drupal_access.module
profiles/multisite_drupal_communities/modules/custom/multisite_og_button/multisite_og_button.info
profiles/multisite_drupal_communities/modules/custom/multisite_og_button/multisite_og_button.install
profiles/multisite_drupal_communities/modules/custom/multisite_og_button/multisite_og_button.module
profiles/multisite_drupal_communities/modules/custom/multisite_og_button/multisite_og_button.test
profiles/multisite_drupal_communities/modules/custom/og_content_type_admin/og_content_type_admin.install
profiles/multisite_drupal_communities/modules/custom/og_content_type_admin/og_content_type_admin.module
profiles/multisite_drupal_communities/modules/custom/og_content_type_admin/tests/og_content_type_admin.extra.test
profiles/multisite_drupal_communities/modules/custom/subscriptions_og/subscriptions_og.install
profiles/multisite_drupal_communities/modules/custom/subscriptions_og/subscriptions_og.module

multisite_drupal_communities/modules

NEXTEUROPA-5919 : Fix coding standards in

---

profiles/multisite_drupal_standard/multisite_drupal_standard.install

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-6017

NEXTEUROPA-6017: remove activation of nexteuropa feature for existing

---

profiles/drupal-org.make

NEXTEUROPA-6013: up colorbox to 2.10

---

sites/all/modules/custom/tmgmt_dgt_html/inc/tmgmt_dgt.format.html.inc
sites/all/modules/custom/tmgmt_dgt_html/templates/tmgmt_dgt_html_template.tpl.php
sites/all/modules/custom/tmgmt_dgt_html/tmgmt_dgt_html.info
sites/all/modules/custom/tmgmt_dgt_html/tmgmt_dgt_html.module

Added module to allow TMGMT translators to use the DGT approved XHTML format.

Added DGT approved HTML format

---

resources/multisite_drupal_standard.make

1
Merge pull request #122 in NEXTEUROPA/platform-dev from hotfix/MULTISITE-6327 to master

NEXTEUROPA-6370: cherry pick 7fe51e7044225b9f78b9c9737633b8987d7d1f20 -m

---

profiles/multisite_drupal_core/patches.make
profiles/multisite_drupal_core/patches/SA-CORE-2015-004.patch

security update
https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-6303

NEXTEUROPA-6303: integrate SA CORE 004

---

resources/drupal-core.make
resources/patches/SA-CORE-2015-004.patch

NEXTEUROPA-6306: add patch for SA-CORE-2015-004

---

resources/multisite_drupal_standard.make

- up module to 2.0-beta1
- up patch

NEXTEUROPA-6256: update media module

---

resources/multisite_drupal_standard.make

I poorly resolved a conflict and, mea culpa.

fix my own mistake

---

profiles/multisite_drupal_communities/themes/ec_resp_17
profiles/multisite_drupal_communities/themes/ec_resp_20
profiles/multisite_drupal_standard/themes/ec_resp_17
profiles/multisite_drupal_standard/themes/ec_resp_20

fix symlink ec_resp_20

---

profiles/common/themes/ec_resp/css/ec_resp.css
profiles/common/themes/ec_resp/css/less/menu.less

Updated navbar active link to make it more readable

MULTISITE-7634 - Fix accessibility issue

---

profiles/common/modules/custom/taxonomy_browser/css/ec-default/style.css

Background colors were wrongly formatted

HOTFIX/MULTISITE-7694 - Fix CSS in taxonomy browser

---

profiles/common/themes/ec_resp/ec_resp.info

MULTISITE-7770: Update ec_resp.info to match the platform version

---

profiles/common/modules/custom/ecas/ecas_extra/ecas_extra.module
profiles/common/modules/custom/ecas/ecas_extra/ecas_extra.test
profiles/common/modules/custom/ecas/ecas_extra/includes/views/ecas_extra.views_default.inc

NEXTEUROPA-3626 : Fix namespacing of Deny Account action in the ECAS

---

profiles/common/modules/features/idea/idea_core/idea_core.install
profiles/common/modules/features/multi_user_blog/multi_user_blog.install

NEXTEUROPA-3892 : Rate widget not correctly removed when features are

---

resources/multisite_drupal_standard.make

NEXTEUROPA-7438: update apacheSolr to 1.8

---

resources/multisite_drupal_standard.make

NEXTEUROPA-7443: up ds module to 2.8

---

resources/multisite_drupal_standard.make

NEXTEUROPA-7442: update jquery_update to 2.7

---

resources/multisite_drupal_standard.make

Fix error Recoverable fatal error: Argument 1 passed to password_policy_password_element_alter

MULTISITE-8185: add patch to password_policy

---

profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.module

Notice: Undefined offset: 0 in nexteuropa_multilingual_preprocess_field()

NEXTEUROPA-7457: fix for php notice

---

tests/features/bootstrap/FeatureContext.php

- improve 'enableFeatureSet' function
- add 'cleanFeatureSet' function for @AfterScenario

NEXTEUROPA-7565: improve enableFeatureSet context

---

resources/multisite_drupal_standard.make

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-7797

NEXTEUROPA-7797: Update MPDF to the latest release.

---

profiles/common/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.sanitize.inc

https://webgate.ec.europa.eu/CITnet/jira/browse/MULTISITE-8047

MULTISITE-8047 fix xss filter for tokens used in a tag as href

---

profiles/common/modules/features/e_library/e_library_og/e_library_og.context.inc
profiles/common/modules/features/links/links_og/links_og.context.inc
profiles/common/modules/features/news/news_og/news_og.context.inc
profiles/common/modules/features/wiki/wiki_og/wiki_og.context.inc

Removed an obsolete debug statement in og_news context

MULTISITE-8110 Removed obsolete debug

---

resources/multisite_drupal_standard.make

Fix error when switching file from Public to Private destination

MULTISITE-8239:  Add patch for file_entity

---

resources/multisite_drupal_standard.make

remove the unwanted description on exposed filters

NEXTEUROPA-7788: add patch for views

---

resources/multisite_drupal_standard.make

NEXTEUROPA-8218: up field group

---

profiles/multisite_drupal_communities/modules/custom/multisite_drupal_access/multisite_drupal_access.module

fix node access problem on group content for unpublished content

MULTISITE-8340: manage node access

---

profiles/common/modules/features/nexteuropa_geofield/nexteuropa_geofield.module

https://webgate.ec.europa.eu/CITnet/jira/browse/MULTISITE-8614

MULTISITE-8614 fix

---

resources/multisite_drupal_standard.make

to fix PHP Notice: Undefined property: stdClass::$status_message

NEXTEUROPA-7651: add patch for apachesolr

---

resources/multisite_drupal_standard.make

The correct pull request. d.o issue https://www.drupal.org/node/2489134

NEXTEUROPA-8555: TMGMT does not process links

---

resources/multisite_drupal_standard.make

fix error: Search pages tabs dissapear with update to 7.x-1.7

MULTISITE-7322: add patch for apachesolr

---

profiles/common/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.module

See https://webgate.ec.europa.eu/CITnet/jira/browse/MULTISITE-8308 for more info.

MULTISITE-8308: preventing trigger of a second batch process.

---

profiles/multisite_drupal_core/patches.make
profiles/multisite_drupal_core/patches/SA-CORE-2016-001.patch

NEXTEUROPA-9253: SA-CORE-2016-001

---

resources/multisite_drupal_standard.make

Together with Victor we are creating this pull request.

NEXTEUROPA-9311 : changing the version for link module

---

resources/multisite_drupal_standard.make

fix "Feeds Import Not Saving Geofield"

NEXTEUROPA-9318: patch geofield

---

profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.callbacks.inc

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-9311

NEXTEUROPA-9311-2 : Don't add the language suffix if already exists

---

profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.admin.inc
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.install
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.module

Nexteuropa PIWIK module improvements. More details inside ticket.

Nexteuropa 9589

---

profiles/common/modules/custom/tmgmt_poetry/tests/tmgmt_poetry_test.install
profiles/common/modules/custom/tmgmt_poetry/tests/tmgmt_poetry_test.module
tests/features/tmgmt/tmgmt_poetry.feature

This pull request makes #392 obsolete.

NEXTEUROPA-8342: Provide behat test for NEXTEUROPA-8226

---

profiles/common/modules/custom/tmgmt_poetry/tests/tmgmt_poetry_test.module

Additional credentials in hook_init( until credentials for poetry_test are moved to build script)

Adding user and password to fix develop NEXTEUROPA-9801

---

profiles/common/modules/custom/tmgmt_workbench/includes/tmgmt_workbench.ui.inc
profiles/common/modules/custom/tmgmt_workbench/tmgmt_workbench.module
profiles/common/modules/features/nexteuropa_multilingual/src/nexteuropa_multilingual.behat.inc
tests/features/tmgmt/tmgmt_workbench.feature

I had an issue with upper case and lower case branche names, so here is a second pull request that makes #416 obsolete.

NEXTEUROPA-9945: TMGMT Poetry - Enforce usage of TMGMT Workbench Moderation plugin

---

profiles/multisite_drupal_communities/multisite_drupal_communities.info
profiles/multisite_drupal_standard/multisite_drupal_standard.info
resources/multisite_drupal_standard.make

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-8807

NEXTEUROPA-8807 : install and enable the fast404 module

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.install

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-9635

NEXTEUROPA-9635 : wrong permissions for default user roles

---

profiles/common/modules/custom/ecas/includes/ecas.inc

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-9753

NEXTEUROPA-9753 : add ecas_login_check in the hook_init

---

profiles/common/modules/custom/ecas/includes/ecas.inc
profiles/common/modules/custom/ecas/libraries/phpcas/CAS.php

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-9753

nexteuropa-9753: fixes scenario 'deny authentification' into ELI site

---

build.properties.dist
build.test.xml
composer.json
composer.lock
tests/behat.yml.dist
tests/features/tmgmt/tmgmt_poetry.feature
tests/src/Context/PhantomjsContext.php

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-5204

 NEXTEUROPA-5204: Make PhantomJS available for behat (using composer)

---

profiles/common/modules/custom/tmgmt_poetry/inc/tmgmt_poetry.webservice.inc

Save original message file from DGT before working on it

---

profiles/common/modules/custom/tmgmt_workbench/includes/tmgmt_workbench.plugin.inc
tests/features/multilingual.feature

[Jira issue here](https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-9998)

NEXTEUROPA-9998 fix saveTranslation method, dont delete the url alias

---

profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.callbacks.inc

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-10210

nexteuropa-10210: adds fix language negotiation prefix fallback

---

profiles/common/modules/custom/tmgmt_workbench/tmgmt_workbench.module

Only block sending again if there is still jobs pending

---

resources/multisite_drupal_standard.make

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-10413

nexteuropa-10413: update Features module (2.7 to 2.9)

---

profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.module

Don't display translation warning if empty variable

---

profiles/common/modules/features/nexteuropa_metatags/nexteuropa_metatags.features.metatag.inc
profiles/common/modules/features/nexteuropa_metatags/nexteuropa_metatags.module

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-10605

Add a viewport tag in nexteuropa metatags

---

profiles/common/modules/custom/tmgmt_workbench/tmgmt_workbench.module
profiles/common/modules/features/nexteuropa_multilingual/src/nexteuropa_multilingual.behat.inc
tests/features/tmgmt/tmgmt_poetry.feature

See issue https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-10639

Add behat test about requesting a new translation

---

profiles/common/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.module

This reverts commit 5a5721f03b1ed103c1ecd1e94558da122425002b.

Revert "NEXTEUROPA-3109"

---

resources/multisite_drupal_standard.make

During latest update of OG module to version 2.9 we've noticed some of unexpected problems. Please find more details in the ticket.

NEXTEUROPA-10838: Rolling back updates for the OG module

---

profiles/common/modules/features/nexteuropa_multilingual/src/nexteuropa_multilingual.behat.inc
tests/features/language_negociation.feature

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-11161

NEXTEUROPA-11161 Add behat test for changed language prefix

---

profiles/common/modules/features/nexteuropa_core/nexteuropa_core.views_default.inc

NEXTEUROPA-11329
Command after deployment:
```drush cc views```

NEXTEUROPA-11329 Fix the plain text format on core view

---

resources/multisite_drupal_standard.make

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-11192

NEXTEUROPA-11192: update xmlsitemap to version 2.3

---

profiles/common/modules/custom/multisite_drupal_language_negociation/multisite_drupal_language_negociation.module

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-11451

NEXTEUROPA-11451: fix if the entity isn't a node

---

resources/multisite_drupal_standard.make

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-11189

NEXTEUROPA-11189: Updating media_youtube module '2.0-rc5' to '3.0'

---

profiles/common/modules/custom/tmgmt_poetry/inc/tmgmt_poetry.webservice.inc
profiles/common/modules/custom/tmgmt_poetry/plugins/tmgmt_poetry.plugin.inc
profiles/common/modules/custom/tmgmt_poetry/tests/tmgmt_poetry_test.module

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-11194

nexteuropa-11194: adding the watchdog_exception

---

resources/drupal-core.make

[core] Security fix : SA-CORE-2016-002

---

profiles/common/themes/ec_resp/templates/global/page.tpl.php

NEXTEUROPA-11139 Check $svg_logo exists in page.tpl.php in order to avoid error messages. 

---

profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.callbacks.inc

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-10210

NEXTEUROPA-10210 - fix language detection

---

resources/multisite_drupal_standard.make

Flexible Purge module can now be downloaded from d.o.

NEXTEUROPA-11579: Add Flexible Purge module as contrib

---

profiles/common/modules/custom/nexteuropa_token/modules/nexteuropa_token_ckeditor/includes/nexteuropa_token_ckeditor.tmgmt_poetry.inc
profiles/common/modules/custom/tmgmt_poetry/tmgmt_poetry.info
profiles/common/modules/custom/tmgmt_poetry/tmgmt_poetry.install

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-11625

NEXTEUROPA-11625 : add loop to replace every tokens

---

resources/multisite_drupal_standard.make

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-11039

NEXTEUROPA-11039: Update the module entityreference

---

resources/multisite_drupal_standard.make

Improve workbench moderation revision history performance.

NEXTEUROPA-12122

---

profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.callbacks.inc
resources/multisite_drupal_standard.make

This adds the patch for NEXTEUROPA-12122 into 2.2.

2.1 support

---

resources/multisite_drupal_standard.make

Prevent unnecessary DB query and cache_set by CSS Injector module.

NEXTEUROPA-12128

---

profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.callbacks.inc
resources/multisite_drupal_standard.make
resources/patches/bootstrap_process_html_tag-2201779.patch

* NEXTEUROPA-12103
* NEXTEUROPA-12128
* Revert tag and fix CS

Merge 2.1-support back into master

---

profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.callbacks.inc

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-11767

NEXTEUROPA-11767: remove language suffix for private files.

---

resources/multisite_drupal_standard.make

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-12137

NEXTEUROPA-12137 - Upgrade media youtube module to 7.x-3.0

---

phpcs-ruleset.xml

phpcs-ruleset.xml : fix extensions exclusion

---

profiles/common/modules/custom/nexteuropa_token/tests/nexteuropa_token.behat.inc
tests/features/bootstrap/FeatureContext.php
tests/features/nexteuropa_token/handling_invalid_wysiwyg_token.feature

This PR includes change of FeatureContext. I've changed clearing watchdog behaviour from the step level to the scenario level. Now watchdog will be cleared before each scenario. That solution is giving us opportunity to interact with watchdog during given scenario.

NEXTEUROPA-11351: Behat test for checking invalid tokens

---

profiles/common/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.module

Fix access to solr settings page for admin

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.features.user_permission.inc
profiles/common/modules/features/cce_basic_config/cce_basic_config.install
tests/features/page_layout.feature

NEXTEUROPA-11884 Remove permission for anonymous users to access user profiles

---

profiles/common/modules/custom/tmgmt_poetry/inc/tmgmt_poetry.webservice.inc

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-12320

NEXTEUROPA-12320: revert the ticket Bugfix/nexteuropa 11340

---

profiles/common/modules/features/nexteuropa_communities/nexteuropa_communities.info
profiles/common/modules/features/nexteuropa_communities/nexteuropa_communities.install
profiles/common/modules/features/nexteuropa_communities/nexteuropa_communities.module
profiles/common/modules/features/nexteuropa_communities/nexteuropa_communities.strongarm.inc

and a site-wide token for detection trigger
MULTISITE-11864

Add a context negotiation for communities

---

profiles/common/modules/features/nexteuropa_communities/nexteuropa_communities.module

Add a check to avoid potential errors with context handler

---

profiles/common/modules/features/nexteuropa_integration/nexteuropa_integration.features.inc

Use Info site producer id for departments and remove producer id for news.

NEXTEUROPA-10100

---

build.package.xml

Improvment for init of private_file directory

---

build.test.xml

Phing target: rebuild-node-access

---

tests/features/piwik.feature

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-12114

NEXTEUROPA-12114: behat test for piwik

---

resources/composer.json
resources/composer.lock

Security update - use Guzzle 6.2.1+ and update dependencies.

NEXTEUROPA-12446

---

profiles/common/themes/ec_resp/templates/global/page.tpl.php

@Fefaine , ready for review & merge

NEXTEUROPA-12458: Make EC Logo alt text translatable

---

profiles/common/themes/ec_resp/template.php

Ready for review & merge @Fefaine

NEXTEUROPA-12509: Correct translatables in template.php

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.module

bugfix/NEXTEUROPA-12512 WYSIWYG - Add full_html_track to html filters list

---

profiles/common/modules/features/nexteuropa_communities/nexteuropa_communities.module

Added an URL wildcard in order to load communities from URLs

---

resources/drupal-core.make

FIx empty label on error validation message

---

profiles/common/modules/features/nexteuropa_webtools/nexteuropa_webtools.module

added check to avoid throwing unwanted error
NEXTEUROPA-12160

Fix file insert with webtools

---

profiles/common/modules/features/nexteuropa_communities/nexteuropa_communities.module

Fix context handler in nexteuropa_communities

---

resources/multisite_drupal_standard.make

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-12711

NEXTEUROPA-12711: Upgrade Piwik module from 2.7 to 2.9.

---

composer.json
composer.lock

NEXTEUROPA-12801 Composer: update coder version in master

---

composer.json
composer.lock

NEXTEUROPA-12801 Composer: update coder version

---

CONTRIBUTING.md
contributing.json

chore(configuration): check format of commit messages with gitmagic

---

profiles/common/modules/custom/tmgmt_poetry/plugins/tmgmt_poetry.plugin.inc
profiles/common/modules/custom/tmgmt_poetry/tmgmt_poetry_mock/src/Mock/PoetryMock.php
profiles/common/modules/custom/tmgmt_poetry/tmgmt_poetry_mock/tmgmt_poetry_mock.behat.inc
tests/features/tmgmt/tmgmt_poetry.feature
tests/src/Context/MinkContext.php

fix(multilingualism): when metadata sent to poetry contains an ampersand errors occur

---

profiles/common/modules/custom/tmgmt_poetry/plugins/tmgmt_poetry.plugin.inc
profiles/common/modules/custom/tmgmt_poetry/tmgmt_poetry_mock/src/Mock/PoetryMock.php
profiles/common/modules/custom/tmgmt_poetry/tmgmt_poetry_mock/tmgmt_poetry_mock.behat.inc
tests/features/tmgmt/tmgmt_poetry.feature
tests/src/Context/MinkContext.php

fix(multilingualism): when metadata sent to poetry contains an amperand errors occur

---

profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.module

Fix the use of entity_uri in nexteuropa_multilingual

---

profiles/common/modules/features/nexteuropa_communities/nexteuropa_communities.context.inc

MULTISITE-12675 add "_any_" condition on communities context

Up communities context

---

resources/multisite_drupal_standard.make

Add patch to workbench moderation to prevent error in shutdown function

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.install
profiles/common/modules/features/multisite_wysiwyg/ckeditor/plugins/link_hreflang/plugin.js
profiles/common/modules/features/multisite_wysiwyg/multisite_wysiwyg.behat.inc
profiles/common/modules/features/multisite_wysiwyg/multisite_wysiwyg.module
tests/features/multisite_wysiwyg/rich_text_editing.feature
tests/features/nexteuropa_token/handling_invalid_wysiwyg_token.feature

Define the link_hreflang ckeditor plugin for the https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-12797
Needs:
* drush updated
* drush cc all

feat(Contributing): Add link_hreflang ckeditor plugin

---

profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.module

fix(multilingual): do not use und in alias for i18n contents

---

profiles/common/modules/custom/tmgmt_poetry/tmgmt_poetry_mock/tmgmt_poetry_mock.install

refactor(multilingualism): use representative values for the DGT mock connector organization configuration

---

profiles/common/modules/custom/multisite_config/lib/Drupal/filter/Config.php
profiles/common/modules/custom/nexteuropa_token/nexteuropa_token.module
profiles/common/modules/features/cce_basic_config/cce_basic_config.install

https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-97

fix(contributing): Fix the internal link token not visible.

---

profiles/common/modules/custom/nexteuropa_token/modules/nexteuropa_token_ckeditor/nexteuropa_token_ckeditor.module
profiles/common/modules/features/nexteuropa_webtools/nexteuropa_webtools.module

https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-105

fix(contributing): Fix the empty popup 'Insert internal content'.

---

resources/multisite_drupal_standard.make

https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-1

fix(contributing): Apply contrib patch on the module wysiwyg '2414575'.

---

profiles/common/themes/ec_resp/template.php

style(site template): do not print class attribute of a link when it is empty

---

profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.module
tests/features/frontend_cache_purge.feature
tests/src/Context/DrupalContext.php

feat(interoperability): trigger cache purge rules as well on non-moderated content

---

profiles/common/modules/custom/tmgmt_poetry/plugins/tmgmt_poetry.ui.inc
profiles/common/modules/custom/tmgmt_poetry/tmgmt_poetry_mock/src/Mock/PoetryMock.php
resources/composer.json
resources/composer.lock
resources/multisite_drupal_standard.make
tests/behat.api.yml.dist
tests/behat.i18n.yml.dist
tests/behat.yml.dist
tests/features/multilingual.feature
tests/features/tmgmt/tmgmt_poetry.feature

chore(configuration): make screenshots on failing tests

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.install
profiles/multisite_drupal_standard/multisite_drupal_standard.info

perf(interoperability): do not enable apachesolr_multisitesearch by default

---

resources/multisite_drupal_standard.make

feat(maintenance): update to flag 3.9

---

profiles/common/modules/custom/multisite_og_navigation_tree/multisite_og_navigation_tree.settings.inc

Change the t() function for vocabulary name translation

---

profiles/common/modules/custom/multisite_og_navigation_tree/multisite_og_navigation_tree.module

Change the t() function for taxonomy term name translation

---

resources/multisite_drupal_standard.make

fix(configuration): downgrade to stable mpdf version 6.1.0

---

profiles/common/modules/features/communities/communities.module

New permission for communities's members

---

Jenkinsfile

* test(jenkins): Reorganise phings.
* test(jenkins): Add notifications.
* test(jenkins): Improve notifications, handle Composer issues.
* test(jenkins): Add context to GitHub status updater.
* test(jenkins): Typo.
* test(jenkins): Use function.

test(jenkins): Reorganise stages and add notifications. (#1019)

---

Jenkinsfile

* test(jenkins): Reorganise phings.
* test(jenkins): Add notifications.
* test(jenkins): Improve notifications, handle Composer issues.
* test(jenkins): Add context to GitHub status updater.
* test(jenkins): Typo.
* test(jenkins): Use function.

Merge master back to branch

---

tests/src/Context/FrontendCacheContext.php

BUGFIX for NEPT-80 merged previously.
Fixing 'frontend cache purge' tests.

fix(test): fixing 'frontend cache purge' tests

---

resources/multisite_drupal_standard.make

fix: update to latest alpha release.

NEPT-232: Error when editing paragraph - apply patch to title module

---

resources/multisite_drupal_standard.make

https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-130

fix(contributing): Upgrade Display suite module to 7.x-2.14

---

resources/multisite_drupal_standard.make

https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-121

fix(contributing): #2801239 Simplenews: Patch entity cache issue.

---

profiles/multisite_drupal_standard/multisite_drupal_standard.info

This reverts commit 8701966abb063f2e8d739c976fb8a7463ed8b932.

Revert "feat(maintenance) disable hard dependency of contact NEPT-403"

---

build.properties.dist

https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-424

improvement(maintenance) NEPT-424 - Add tests folder into the phpcs configuration.

---

profiles/common/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.module
tests/features/multisite_drupal_toolbox.feature

https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-63

Theme status messages not overridable

---

resources/drupal-core.make

Impact the build as it implies a make file modification

Nept 224 : Apply 980144-98_0.patch

---

profiles/common/modules/custom/version_management/version_management.js

https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-222

fix(maintenance) NEPT-222 - Fix version_management.js.

---

resources/multisite_drupal_standard.make

https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-444

fix(configuration): NEPT-444 - Add CDN module.

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.install

on community profile. This is a workaround until NEPT-535 is done

NEPT-182: feat(multilingualism) Add a condition to not enable feature set standard

---

.gitignore
Jenkinsfile
README.md
build.package.xml
build.properties.dist
build.test.xml
build.xml
composer.json
composer.lock
tests/behat.api.yml.dist
tests/behat.i18n.yml.dist
tests/features/content_level_language_switcher.feature
tests/features/field.multilingual.feature
tests/features/language_coverage.feature
tests/features/language_negociation.feature
tests/features/multilingual.feature
tests/features/multilingual_admin.feature
tests/features/second_favorite_language.feature
tests/features/site_level_language_switcher.feature
tests/features/splash_screen.feature
tests/features/tmgmt/tmgmt_poetry.feature
tests/features/tmgmt/tmgmt_workbench.feature
tests/src/Context/IntegrationLayerContext.php
tests/src/Context/TaxonomyContext.php
tests/src/Context/VariableContext.php
tests/src/Context/WebtoolsContext.php

This reverts commit 7b0878b3e5a07495e79f787ec14246cc4cab151a.

Revert "NEPT-153: Behat parallelization (#1112)" - NEPT-576

---

resources/multisite_drupal_standard.make

NEPT-350 for release 2.4: Update Coffee contrib module to version 7.x-2.3

---

resources/multisite_drupal_standard.make

NEPT-350 for master: Update Coffee contrib module to version 7.x-2.3

---

profiles/multisite_drupal_communities/modules/custom/multisite_drupal_features_set_standard
profiles/multisite_drupal_communities/modules/custom/nexteuropa_ds_layouts
profiles/multisite_drupal_communities/modules/custom/nexteuropa_formatters
profiles/multisite_drupal_communities/modules/custom/tmgmt_dgt_html
profiles/multisite_drupal_communities/modules/custom/tmgmt_poetry
profiles/multisite_drupal_communities/modules/features/multisite_review
profiles/multisite_drupal_communities/modules/features/nexteuropa_dgt_connector
profiles/multisite_drupal_communities/modules/features/nexteuropa_event
profiles/multisite_drupal_communities/modules/features/nexteuropa_faq
profiles/multisite_drupal_communities/modules/features/nexteuropa_feature_set
profiles/multisite_drupal_communities/modules/features/nexteuropa_geofield
profiles/multisite_drupal_communities/modules/features/nexteuropa_mediagallery
profiles/multisite_drupal_communities/modules/features/nexteuropa_news
profiles/multisite_drupal_communities/modules/features/nexteuropa_trackedchanges

Clone of the PR https://github.com/ec-europa/platform-dev/pull/1191 for merge against the master branch.

NEPT-618: Aligning symlinks between standard and community profile

---

profiles/multisite_drupal_communities/modules/custom/multisite_drupal_features_set_og/multisite_drupal_features_set_og.info

Recently developed features were not added to the community profile feature set. This pull request is fixing that missing part and aligns the standard and community profile.

NEPT-622: Aligning the feature sets - fix(maintenance)

---

resources/multisite_drupal_standard.make

NEPT-567: Prevent wrong missing module when rebuilding registry - fix(maintenance)

---

profiles/multisite_drupal_communities/modules/custom/multisite_drupal_features_set_og/multisite_drupal_features_set_og.info

Adding the missing GeoJson Feeds feature to the community profile feature set.

NEPT-622: Adding missing GeoJson Feeds feature - fix(maintenance)

---

profiles/common/modules/custom/tmgmt_workbench/tmgmt_workbench.module
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/plugins/tmgmt_poetry.ui.inc
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/tmgmt_poetry.module
tests/features/multilingual.feature
tests/features/tmgmt/tmgmt_poetry_translations.feature
tests/features/tmgmt/tmgmt_workbench.feature

Main goal was to remove the tmgmt_poetry module functionalities from the tmgmt_workbench module and make it possible to use other translators which are available for the tmgmt module.

NEPT-118: Resolve the conflict of the TMGMT translators.

---

resources/drupal-core.make
tests/behat.yml.dist
tests/features/contact_form.feature
tests/src/Context/FormContext.php

Prevents the change of e-mail addresses of connected users when they are on the contact forms

NEPT-548: Prevents the change of e-mail addresses of connected users on contact forms.

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.features.field_base.inc
profiles/common/modules/features/cce_basic_config/cce_basic_config.info
profiles/common/modules/features/cce_basic_config/cce_basic_config.install

feat(Configuration & Maintenace): NEPT-640 - Move "body" field base declaration from the feature to the hook_install

feat(Configuration & Maintenace): NEPT-640 - Move "body" field base declaration

---

resources/multisite_drupal_standard.make

NEPT-643: Update contrib module Better Exposed Filters.

---

profiles/common/modules/features/multisite_metatags/multisite_metatags.install
profiles/common/modules/features/nexteuropa_metatags/nexteuropa_metatags.features.metatag.inc
profiles/common/modules/features/nexteuropa_metatags/nexteuropa_metatags.helpers.inc
profiles/common/modules/features/nexteuropa_metatags/nexteuropa_metatags.install
profiles/common/modules/features/nexteuropa_metatags/nexteuropa_metatags.module
profiles/common/themes/ec_resp/templates/global/html.tpl.php

Also add a warning if the X-UA-Compatible meta is set by the user.

NEPT-132: Metatag contrib security update.

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.install
profiles/common/modules/features/cce_basic_config/cce_basic_config.strongarm.inc

NEPT-738: Add a hook to update the platform version in status report - fix(chore)

---

resources/multisite_drupal_standard.make

https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-743

nept-743 - update the contrib module 'views' to 7.x-3.15

---

profiles/common/modules/features/nexteuropa_trackedchanges/nexteuropa_trackedchanges.module

…e problem with the drush rr (#1279)

NEPT-627: merge from master to release-2.4

---

CHANGELOG.md
tests/behat.yml.dist
tests/features/drupal_mail.feature
tests/src/Context/DrupalMailContext.php

Implemented solution is provided via new custom Behat DrupalMailContext context.
It doesn't need any additional modules or settings to run it.

NEPT-316: Implement the solution for testing the mail features

---

profiles/common/modules/features/nexteuropa_multilingual/README.md
tests/features/multilingual_admin.feature
tests/features/tmgmt/tmgmt_workbench.feature
tests/src/Context/VariableContext.php

https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-247

Nept-247: add behat test to custom the variable nexteuropa_multilingual_warning_message_languages

---

Jenkinsfile

NEPT-519: Build and test standard and communities profiles

---

phpcs-ruleset.xml
profiles/common/modules/custom/nexteuropa_varnish/README.md
profiles/common/modules/custom/nexteuropa_varnish/includes/cache_purge_rule.ui.inc
profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.admin.inc
profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.install
profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.module
profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.rules.admin.inc
tests/features/frontend_cache_purge.feature
tests/src/Context/FrontendCacheContext.php

Custom branch to resolve conflict in the initial PR #1320.
PR to update the 2.4 branch with the NEPT-775 functionality
NEPT-775: The default purge rule functionality
NEPT-775: Fixing problem with the Behat tests + docs
NEPT-775: Changing the order of steps in Behat scenarios
NEPT-775: Changing the order of steps in Behat scenarios + case for new nodes without rules
NEPT-775: Tweak the new node case
NEPT-775: Extending default rule usage. Excluding new nodes, including translations.
NEPT-775: Removing a case for sending purge request on the node creation
NEPT-775: Stabilizing and implementing the code review suggestions
NEPT-775: Implementing suggestions from the Code Review
NEPT-744: Improved comment readability

NEPT-775: PR for 2.4 with the resolved confilcts

---

profiles/common/modules/features/communities/communities.views_default.inc

NEXTEUROPA-13216: Fix insufficient access check on views in communities

---

profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.install
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.install.inc
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.module
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.rule.admin.inc

Follow up of the #1259 PR to implement the suggestions proposed by the QA team.

NEPT-717: Advanced PIWIK rules feature - QA suggestions

---

profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.install
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.install.inc
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.rule.admin.inc

Follow up of the #1324 PR to implement the suggestions proposed by the QA team.

NEPT-717: Advanced PIWIK rules feature - QA suggestions - master

---

profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.install
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.install.inc
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.rule.admin.inc
profiles/common/modules/features/cce_basic_config/cce_basic_config.install
profiles/multisite_drupal_communities/modules/custom/nexteuropa_ds_layouts
profiles/multisite_drupal_communities/modules/custom/nexteuropa_formatters
resources/multisite_drupal_standard.make

Follow up of the #1324 PR to implement the suggestions proposed by the QA team.

NEPT-717: Advanced PIWIK rules feature - QA suggestions - 2.4

---

profiles/common/modules/custom/language_selector_site/language_selector_site.module
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.install
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.install.inc
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.module
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.rule.admin.inc
profiles/common/modules/features/cce_basic_config/cce_basic_config.install
profiles/common/modules/features/cce_basic_config/cce_basic_config.strongarm.inc
profiles/common/modules/features/nexteuropa_feature_set/multisite_drupal_features_set_standard/multisite_drupal_features_set_standard.info
profiles/multisite_drupal_communities/modules/custom/nexteuropa_ds_layouts
profiles/multisite_drupal_communities/modules/custom/nexteuropa_formatters
resources/multisite_drupal_standard.make
resources/patches/feature_set-add_categories_management-nexteuropa_4459-nept_930.patch
tests/features/feature_set/nexteuropa_trackedchanges_set.feature
tests/features/piwik.feature
tests/src/Context/MinkContext.php

To follow the changes applied on the master branch and to address those in the context of a new theme there is a need to continuously align the feature branch.

Aligning the europa-atomium feature branch with the master.

---

profiles/common/modules/custom/nexteuropa_varnish/includes/cache_purge_rule.ui.inc
profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.admin.inc
profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.install
profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.module
profiles/common/modules/custom/nexteuropa_varnish/src/Entity/PurgeRule.php
profiles/common/modules/custom/nexteuropa_varnish/src/PurgeRuleController.php
tests/features/frontend_cache_purge.feature

Creation of the purge rules caching

NEPT-799: Implement the logic comparing paths between 2 node successive revisions

---

resources/multisite_drupal_standard.make

* NEPT-1039: Add undefined_group_in_i18n-2882048-2.patch
* NEPT-1039: Come back to version 1.21
* NEPT-1039: Simplify the title definition process
* NEPT-1039: update to the lastest patch

NEPT-1039: Merge to 2.4

---

resources/multisite_drupal_standard.make
resources/patches/media-inputs_whitelist-1026.patch

* NEPT-1026: Add custom patch designed for media 2.0-beta1
* NEPT-1026: Apply feedback from code review
* NEPT-1026: Fix typo
* NEPT-1026: Add wysiwyg feature
* NEPT-1026: Change token name

NEPT-1026: Add custom patch designed for media 2.0-beta1 (#1429)

---

profiles/common/modules/custom/ecas/includes/ecas.inc

NEPT-611: Fix display of username in watchdog upon logout.

---

UPGRADING.md

NEPT-1033
Add the missing step into UPGRADING.md
- Added: the missing After-upgrade step into UPGRADING.md for Nexteuropa Varnish
```sh
no additional command
```

NEPT-1033: Add the missing step into UPGRADING.md

---

.github/PULL_REQUEST_TEMPLATE.md
profiles/common/modules/custom/ecas/includes/ecas.inc
resources/drupal-core.make

Removing the base path from the purge paths
Add the missing step into UPGRADING.md
Add the Pull Request template
Update Drupal core to version 7.55
Fix display of username in watchdog upon logout

Helper PR to align master with the release-2.4 branch.

---

Jenkinsfile
resources/multisite_drupal_standard.make

NEPT-1015: Change patch for media, issue #2028231 in DO;
NEPT-1140: Remove package stage from Jenkinsfile.
- Changed:
Patch for media, issue #2028231 in DO from # 15 to # 11;
Remove package stage, for building the platform, from Jenkinsfile.
No specific commands are required.

NEPT-1015: merge from master to 2.4 (#1435 and #1447)

---

profiles/common/modules/custom/multisite_config/lib/Drupal/user/Config.php
profiles/common/modules/features/nexteuropa_editorial/nexteuropa_editorial.module
profiles/common/modules/features/nexteuropa_editorial/src/Config.php
resources/multisite_drupal_standard.make
tests/features/editorial_workflow_admin.feature

Editorial team role: Provide failing tests.
- Fixed: Fatal error when updating users editorial team field
- Added: Behat tests
```sh
No commands requiered 
```

NEPT-916: Editorial team role: Provide failing tests.

---

profiles/common/modules/custom/multisite_config/lib/Drupal/user/Config.php
profiles/common/modules/features/nexteuropa_editorial/nexteuropa_editorial.module
profiles/common/modules/features/nexteuropa_editorial/src/Config.php
resources/multisite_drupal_standard.make
tests/features/editorial_workflow_admin.feature

Editorial team role: Provide failing tests.
- Fixed: Fatal error when updating users editorial team field
- Added: Behat tests
```sh
No commands required 
```

NEPT-916: Editorial team role: Provide failing tests. (#1352)

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.info
profiles/common/modules/features/cce_basic_config/cce_basic_config.install
profiles/common/modules/features/nexteuropa_europa_search/README.md
profiles/common/modules/features/nexteuropa_europa_search/nexteuropa_europa_search.info
profiles/common/modules/features/nexteuropa_europa_search/nexteuropa_europa_search.module
profiles/multisite_drupal_standard/multisite_drupal_standard.info
tests/features/search/europa_search.feature

Implement the new header search bars component
- Added: Add dependency of nexteuropa_europa_search feature to cce_basic_config
- Added: Force the activation of nexteuropa_europa_search feature
- Changed: Add a title to the QueryText textfield of the "nexteuropa_europa_search" form
```sh
drush updatedb
```

NEPT-1071: Implement the new header search bars component

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.module
profiles/common/modules/features/cce_basic_config/cce_basic_config.strongarm.inc

Add the breadcrumb block inside the header bottom region
- Added: hook_themes_enabled
```sh
no command to run
```

NEPT-1059: Add the breadcrumb block into the proper europa region.

---

resources/multisite_drupal_standard.make

Change the version of EC_RESP theme to 2.3
- Changed: Change the version of EC_RESP theme.
```sh
no additional commands
```

NEPT-1031: Change the version of EC_RESP theme.

---

resources/multisite_drupal_standard.make

Fix all dev & master version modules on a commit number.
- Added:
- Changed: resources/multisite_drupal_standard.make file
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
no commands
```

NEPT-1205: MULTISITE_18084.

---

resources/multisite_drupal_standard.make

Follow-up of the PR https://github.com/ec-europa/platform-dev/pull/1495
- Changed: resources/multisite_drupal_standard.make file

NEPT-1205: Aligning 2.2 and 2.3 + other minor fixes

---

resources/multisite_drupal_standard.make

Follow-up of the PR https://github.com/ec-europa/platform-dev/pull/1497
- Changed: resources/multisite_drupal_standard.make file

NEPT-1205: Aligning 2.3 with master + other minor fixes

---

resources/multisite_drupal_standard.make

Cleaning the multisite_drupal_standard.make file based on the QA Team input.
- Changed: multisite_drupal_standard.make

NEPT-1205: Aligning 2.5 with master - cleaning multisite_drupal_standard.make

---

profiles/common/modules/custom/nexteuropa_ecl_migrate/nexteuropa_ecl_migrate.module

Add facebook, twitter classes in the footer menu.
- Added: Add facebook, twitter classes in the footer menu.
```sh
no commands
```

Nept 1152: Add facebook, twitter classes in the footer menu.

---

composer.lock

In master and europa-atomium branch, we have the issue :
`Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.`

NEPT-1244: composer.json and composer.lock sync.

---

profiles/multisite_drupal_communities/multisite_drupal_communities.info

NEXTEUROPA-9797
NEXTEUROPA-9797
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
[Insert commands here]
```

Enable nexteuropa_laco by default on community profile

---

tests/features/communities.feature

NEXTEUROPA-13828 - Add behat tests on the community profile to check that no nexteuropa
features/modules are enabled

NEXTEUROPA-13828: Add behat tests for community profile

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.install

Update variable for platform version.
- Added: hook_update_N in cce_basic_config to update the variable for platform version.
```sh
drush updb
```

NEPT-1429: Update variable for platform version

---

profiles/common/modules/custom/nexteuropa_formatters/nexteuropa_formatters.module
profiles/common/modules/custom/nexteuropa_formatters/nexteuropa_formatters_views/src/views/plugins/nexteuropa_core_views_expandable_rows.php
profiles/common/modules/custom/nexteuropa_formatters/templates/expandable.tpl.php

The Expandable component should work with Nexteuropa Formatters modules.

NEPT-1064: Make NextEuropa Formatters compatible with Expandable component.

---

Jenkinsfile
build.properties.dist
build.test.xml
composer.json
composer.lock
phpcs-qa-roadmap.xml
phpcs-ruleset.xml
profiles/common/modules/features/nexteuropa_core/nexteuropa_core.install
resources/multisite_drupal_communities.make
resources/multisite_drupal_standard.make
src/Phing/PhpCodeSnifferConfigurationTask.php
tests/src/Context/MessageContext.php

Addition of qa-automation tools
Changed: Addition of qa-automation tools
Changed: Change permission
Changed: Make release of qa-automation
Changed: Add exceptions for tests
Changed: Test, composer.json qa-automation is not released yet.
Changed: Full PHPCBF run, test site install
Changed: Add codingstandardsignore to fix build
Changed: Update composer.json and lock
Changed: Add more exclusions.
Changed: Update Makefile for the profile communities.
Changed: Add the option -s to phpcs in jenkins.
Changed: Add exclusions for the profil communities.
Changed: Remove duplicate exclusions.
Changed: Update QA-Automation and changes requested.
```sh
drush cc all
```

Nept 804 release 25

---

phpcs-qa-roadmap.xml
profiles/common/modules/features/multisite_mediagallery_core/multisite_mediagallery_core.module

Removed redeclaration of global variable.
- Fixed: emoved redeclaration of global variable.

NEPT-1286: Removed redeclaration of global variable.

---

phpcs-qa-roadmap.xml
profiles/common/modules/features/multisite_mediagallery_community/multisite_mediagallery_community.module

NEPT-1291: Fixed form doc comment in multisite_mediagallery_community.
- Fixed: Fixed form doc comment.

NEPT-1291: Fixed form doc comment in multisite_mediagallery_community.

---

phpcs-qa-roadmap.xml

Improved rule description.
- Fixed: Improved rule description.

NEPT-1303: Improved rule description.

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.module

Made error message translatable.
- Fixed: Made error message translatable.

NEPT-1292: Made error message translatable.

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/ecas/ecas_import_users/ecas_import_users.module

Removed unnecessary check_plains in ecas_import_users.
- Added:
- Fixed: Removed unnecessary check_plains in ecas_import_users.

NEPT-1293: Removed unnecesary check_plains in ecas_import_users.

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/ecas/ecas_group_sync/ecas_group_sync.install
profiles/common/modules/custom/ecas/ecas_import_users/ecas_import_users.install
profiles/common/modules/custom/multisite_cookie_consent/modules/connections/multisite_cookie_rest.testing.inc
profiles/common/modules/features/e_library/e_library_og/e_library_og.install
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/controller/tmgmt_poetry.controller.job.inc

NEPT-1294: Made messages translatable.
- Fixed: Made messages translatable in multisite_cookie_consent, nexteuropa_dgt_connector & e_library

NEPT-1294: Made messages translatable.

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/multisite_drupal_language_negociation/multisite_drupal_language_negociation.module

Made description translatable.
- Fixed: Made description translatable.

NEPT-1297: Made description translatable.

---

phpcs-qa-roadmap.xml
profiles/common/modules/features/likedislike/likedislike.module

Added appropiate role to configuration page.
- Fixed: Added appropiate role to configuration page.

NEPT-1298: Added appropiate role to configuration page.

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/multisite_config/src/ConfigBase.php
profiles/common/modules/custom/multisite_drupal_wiki_toc/multisite_drupal_wiki_toc.module
profiles/common/modules/features/feed_rss_core/feed_rss_core.module
profiles/common/modules/features/multisite_charts/multisite_charts.install

Removed empty lines after inline comments.
- Fixed: NEPT-1287: Removed empty lines after inline comments.

NEPT-1287: Removed empty lines after inline comments.

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/ecas/includes/ecas.inc
profiles/common/modules/custom/multisite_og_navigation_tree/multisite_og_navigation_tree.module
profiles/common/modules/features/communities/communities.module
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/plugins/tmgmt_poetry.ui.inc

Fixed spacing before equal sign.
- Fixed: Fixed spacing before equal sign.

NEPT-1371: Fixed spacing before equal sign.

---

phpcs-qa-roadmap.xml
phpcs-ruleset.xml
profiles/common/modules/custom/multisite_cookie_consent/modules/connections/multisite_cookie_rest.inc
profiles/common/modules/custom/multisite_cookie_consent/modules/connections/multisite_cookie_rest.testing.inc
profiles/common/modules/custom/multisite_create_button/multisite_create_button.test
profiles/common/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.test
profiles/common/modules/custom/multisite_og_button/multisite_og_button.test
profiles/common/modules/custom/multisite_og_navigation_tree/multisite_og_navigation_tree.test
profiles/common/modules/custom/nexteuropa_varnish/includes/cache_purge_rule.ui.inc
profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.module
profiles/common/modules/features/e_library/e_library_standard/tests/e_library_standard.test
profiles/common/modules/features/ec_embedded_video/tests/ec_embedded_video.test
profiles/common/modules/features/ec_world_countries/nuts_regions/nuts_regions.migrate.inc
profiles/common/modules/features/multisite_business_indicators/multisite_business_indicators_community/tests/multisite_business_indicators_community.test
profiles/common/modules/features/multisite_business_indicators/multisite_business_indicators_core/tests/multisite_business_indicators_core.test
profiles/common/modules/features/multisite_business_indicators/multisite_business_indicators_standard/tests/multisite_business_indicators_standard.test
profiles/common/modules/features/multisite_custom_error/tests/multisite_custom_error.extra.test
profiles/common/modules/features/multisite_notifications/multisite_notifications_core/includes/multisite_notifications_core.behat.inc
profiles/common/modules/features/multisite_readspeaker/tests/multisite_readspeaker.test
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_html/inc/tmgmt_dgt.format.html.inc
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_html/tmgmt_dgt_html.module
profiles/common/modules/features/nexteuropa_multilingual/includes/translation.handler.file.inc
profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.module
profiles/common/modules/features/wiki/wiki_core/tests/wiki_core.test

Fix class naming issues
- Fixed:  Fix class naming issues

Nept-1288: Fix class naming issues

---

phpcs-qa-roadmap.xml

Added exclusion rule until standard is defined.
- Fixed: Added exclusion rule until standard is defined.

NEPT-1364: Added exclusion rule until standard is defined.

---

phpcs-qa-roadmap.xml
profiles/common/modules/features/nexteuropa_communities/nexteuropa_communities.info
profiles/common/modules/features/nexteuropa_event/nexteuropa_event.info
profiles/common/modules/features/nexteuropa_faq/nexteuropa_faq.info
profiles/common/modules/features/nexteuropa_mediagallery/nexteuropa_mediagallery.info
profiles/common/modules/features/nexteuropa_news/nexteuropa_news.info

Removed unused attribute.
- Fixed: Removed unused attribute.

NEPT-1311: Removed unused attribute.

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/ecas/README.md
profiles/common/modules/custom/multisite_cookie_consent/modules/connections/README.txt
profiles/common/modules/custom/nexteuropa_data_export/README.md
profiles/common/modules/features/nexteuropa_dgt_connector/README.md
profiles/common/modules/features/nexteuropa_europa_search/README.md

Removed extra newlines from files.
- Fixed: Removed extra newlines from files.

NEPT-1365: Removed extra newlines from files.

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/multisite_config/tests/multisite_config_test/multisite_config_test.features.field_base.inc
profiles/common/modules/custom/nexteuropa_data_export/tests/nexteuropa_data_export_test/nexteuropa_data_export_test.features.field_base.inc
profiles/common/modules/features/cce_basic_config/cce_basic_config.features.field_base.inc
profiles/common/modules/features/communities/communities.features.field_base.inc
profiles/common/modules/features/ec_content_slider/ec_content_slider.features.field_base.inc
profiles/common/modules/features/ec_embedded_image/ec_embedded_image.behat.inc
profiles/common/modules/features/multisite_activity/multisite_activity_core/multisite_activity_core.features.field_base.inc
profiles/common/modules/features/multisite_metatags/multisite_metatags.features.field_base.inc
profiles/common/modules/features/news/news_og/news_og.features.field_base.inc
profiles/common/modules/features/nexteuropa_core/nexteuropa_core.behat.inc
profiles/common/modules/features/nexteuropa_core/nexteuropa_core.features.field_base.inc
profiles/common/modules/features/nexteuropa_event/nexteuropa_event.features.field_base.inc
profiles/common/modules/features/nexteuropa_faq/nexteuropa_faq.features.field_base.inc
profiles/common/modules/features/nexteuropa_mediagallery/nexteuropa_mediagallery.features.field_base.inc
profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.features.field_base.inc
profiles/common/modules/features/nexteuropa_news/nexteuropa_news.features.field_base.inc
profiles/common/modules/features/nexteuropa_notices/nexteuropa_notices.features.field_base.inc
profiles/common/modules/features/nexteuropa_webtools/nexteuropa_webtools.features.field_base.inc

Locked all fields, including body field.
-Fixed: Locked all fields.

NEPT-1306: Locked all fields.

---

phpcs-qa-roadmap.xml
profiles/common/modules/features/cce_basic_config/cce_basic_config.features.ckeditor_profile.inc
profiles/common/modules/features/cce_basic_config/cce_basic_config.install
profiles/common/modules/features/cce_basic_config/cce_basic_config.strongarm.inc
profiles/common/modules/features/ecas_env/README.md

Removed rule.
- Fixed: Removed rule.

NEPT-1308: Removed rule.

---

Jenkinsfile
README.md

CS checks are executed earlier during pipeline execution
- Changed: Pipeline updated to execute CS checks earlier
No command to execute.

NEPT-1484: Execute CS checks earlier in the pipeline

---

profiles/common/modules/features/splash_screen/splash_screen.module

Add a variable on the component splash.
- Changed: the theme_hook of splash
```sh
no commands
```

NEPT-1096: Add a variable on the component splash.

---

profiles/common/modules/custom/nexteuropa_formatters/nexteuropa_formatters.module
profiles/common/modules/custom/nexteuropa_formatters/nexteuropa_formatters_fields/nexteuropa_formatters_fields.module
profiles/common/modules/custom/nexteuropa_formatters/templates/expandable.tpl.php
profiles/common/modules/custom/nexteuropa_formatters/templates/social-icon.tpl.php

Define the component social_icon into nexteuropa_formatters
- Added: the definition of the component social_icon.
```sh
no commands
```

NEPT-1094: Define the component social_icon.

---

composer.json
composer.lock
profiles/common/modules/custom/multisite_create_button/multisite_create_button.module
profiles/common/modules/custom/nexteuropa_formatters/nexteuropa_formatters.module
profiles/common/modules/custom/nexteuropa_formatters/templates/expandable.tpl.php
resources/multisite_drupal_standard.make

Move the logic from the theme into the module and get rid of `theme_dropdown()` function in the theme.
This PR is linked to:
- Theme EC Europa: https://github.com/ec-europa/ec_europa/pull/15
- Theme Atomium: https://github.com/ec-europa/atomium/pull/49
- Theme EC Resp: https://github.com/ec-europa/ec_resp/pull/7

NEPT-1452: Theme cleanup.

---

resources/multisite_drupal_standard.make

Updated captcha module to 1.5.
- Security: Updated captcha module from 1.3 to 1.5.
`drush updb`

NEPT-1509: Updated captcha module to 1.5.

---

resources/multisite_drupal_standard.make
resources/patches/entityreference-autocomplete-constant-control.patch

Add entityreference fix patch.
- Added: entityreference fix patch.
```sh
drush cc all
```

NEPT-1459: Add entityreference fix patch.

---

resources/multisite_drupal_standard.make
resources/patches/entityreference-autocomplete-constant-control.patch

Add entityreference fix patch.
- Added: entityreference fix patch.
```sh
drush cc all
```

NEPT-1459: Add entityreference fix.

---

resources/multisite_drupal_standard.make

Upgrade file_entity module to version 2.4 and add the patch on d.o issue 2893132
- Changed: file_entity module version
```sh
no command
```

NEPT-672: Upgrading file_entity module to latest version.

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/multisite_config/lib/Drupal/field/InstanceField/DefaultFieldHandler.php
profiles/common/modules/custom/nexteuropa_json_field/nexteuropa_json_field.api.php
profiles/common/modules/custom/nexteuropa_lastupdate/nexteuropa_lastupdate.module
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.rule.admin.inc
profiles/common/modules/features/multisite_megamenu/multisite_megamenu.install
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/tmgmt_poetry_mock/tmgmt_poetry_mock.module
profiles/common/modules/features/taxonomy_browser/taxonomy_browser.module
src/Phing/PhpCodeSnifferConfigurationTask.php

Remove PHPCS rule exception for which we have no errors.
- Removed: Exception rule in phpcs-qa file
```sh
no command
```

NEPT-1377: Remove rule for which we have no errors.

---

profiles/common/modules/custom/ecas/ecas_import_users/ecas_import_users.module

Remove unnecessary check_plain.
- Removed: check_plain
```sh
no command
```

NEPT-1255: Remove unnecessary check_plain.

---

resources/multisite_drupal_standard.make

Upgrade file_entity module to commit after version 2.4 with patch on d.o issue 2893132.
- Changed: file_entity module version

NEPT-672: Upgrading file_entity module to latest version

---

resources/composer.json
resources/composer.lock

Add OE Poetry Client to composer dependencies.
- Added: minimum-stability to resources/composer definitions
- Added: prefer-stable to resources/composer definitions
- Added: ec-europa/oe-poetry-client dependency
- Changed: Version of http-mock to ^0.8.1 for better compability

NEPT-1531: Add OE Poetry Client to composer

---

profiles/common/modules/custom/multisite_config/lib/Drupal/user/Config.php
profiles/common/modules/features/nexteuropa_editorial/nexteuropa_editorial.module
profiles/common/modules/features/nexteuropa_editorial/src/Config.php
resources/multisite_drupal_standard.make
tests/features/editorial_workflow_admin.feature

Editorial team role: Provide failing tests
- Added: Behat tests
- Fixed: Fixed: Fatal error when updating users editorial team field
No command required

NEPT-1553: Re-apply NEPT-916: Editorial team role: Provide failing tests

---

profiles/common/modules/custom/nexteuropa_formatters/nexteuropa_formatters_fields/nexteuropa_formatters_fields.module

Merge fix the redirection process that stopped directly after the EU Login process.
- Fixed: the redirection definition in the logout call in the ECAS module.
```sh
No command required
```

NEPT-1176: Merge into 2.5

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/multisite_config/lib/Drupal/field_group/FieldGroupHandler.php

NEPT-1378: Remove unused use statements.

---

resources/multisite_drupal_standard.make

Update fblikebutton to 2.6.
- Security: Updated fblikebutton to 2.6.
No command.

NEPT-1426: Update fblikebutton

---

phpcs-qa-roadmap.xml
phpcs-ruleset.xml

Fix QA automation rules - File appears to be minified and cannot be processed.
- Removed: The rule
```java
<rule ref="Internal.Tokenizer.Exception">
<exclude-pattern>*</exclude-pattern>
</rule>
```
- Added: A rule to exclude nexteuropa_newsroom.
NA.

NEPT-1417  Fix QA automation rules - File appears to be minified and cannot be processed.

---

profiles/common/modules/custom/multisite_config/lib/Drupal/user/Config.php
profiles/common/modules/features/nexteuropa_editorial/src/Config.php

Removed unnecesary user checks and commented db update methods in order to make clear the reasoning behind their use.
- Added: Comments on db calls
- Changed: Removed unnecesary checks

NEPT-1568: Removed unnecesary checks and commented behavior.

---

tests/features/communities.feature

[Insert description here]
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
[Insert commands here]
```

Behat: Fix community scenario

---

profiles/common/modules/features/nexteuropa_core/src/Psr3Watchdog.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/README.md
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/ne_dgt_rules.admin.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/ne_dgt_rules.info
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/ne_dgt_rules.install
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/ne_dgt_rules.module
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/ne_dgt_rules.rules_defaults.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/rules/ne_dgt_rules_actions.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/rules/ne_dgt_rules_conditions.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/rules/ne_dgt_rules_data_types.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/src/DgtRulesTools.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/README.md
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/ne_tmgmt_dgt_ftt_translator.info
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/ne_tmgmt_dgt_ftt_translator.install
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/ne_tmgmt_dgt_ftt_translator.module
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/rules/ne_tmgmt_dgt_ftt_translator_rules.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/Entity/DgtFttTranslatorMapping.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/TMGMTDefaultSubscriber/TmgmtDgtFttSubscriber.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/TMGMTDefaultTranslatorPluginController/TmgmtDgtFttTranslatorPluginController.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/TMGMTDefaultTranslatorUIController/TmgmtDgtFttTranslatorUiController.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/Tools/DataProcessor.php
resources/composer.json
resources/composer.lock

Fast Track Translations feature
- Added:
-- new custom modules: ne_dgt_rules, ne_tmgmt_dgt_ftt_translator
-- new dependencies in the composer.json and changes in the composer.lock
tbd

NEPT-1475: DGT Fast track feature for the 2.3 release

---

resources/multisite_drupal_standard.make

Update for the 'Views' module with the patch.
- Changed:
-- resources/multisite_drupal_standard.make - changing the version and adding the patch

NEPT-1539: Update to the version 3.18 with patch for the views module

---

build.properties.dist
tests/features/content_types/article_ec_europa.feature

Upgrade the version of EC_EUROPA to 0.0.4.
- Changed: The version of EC_EUROPA to 0.0.4.
```sh
no commands.
```

NEPT-1577: Upgrade the version of EC_EUROPA.

---

build.properties.dist
resources/multisite_drupal_standard.make
tests/features/content_types/article_ec_europa.feature

Remove temporary workaround for username rendering in nodes.
- Fixed: Remove temporary workaround for username rendering in nodes.
```sh
no commands
```

NEPT-1586: Remove temporary workaround for username rendering in nodes.

---

profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/rules/ne_dgt_rules_actions.inc

Add the possibility to customize the variable 'WorkflowCode' into the action.
- Added: Add the possibility to customize the variable 'WorkflowCode' into the action.
```sh
no commands
```

NEPT-1588: Add the possibility to customize the variable 'WorkflowCode' into the action.

---

profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/src/DgtRulesTools.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/TMGMTDefaultSubscriber/TmgmtDgtFttSubscriber.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/TMGMTDefaultTranslatorPluginController/TmgmtDgtFttTranslatorPluginController.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/Tools/DataProcessor.php

Checking the translator type to correct dispatch upcoming translations.
- Added: Checking the translator type to correct dispatch upcoming translations.
```sh
no commands
```

NEPT-1590: Checking the translator type to correct dispatch upcoming translations.

---

resources/multisite_drupal_standard.make

Remove module field_collection from core.
- Removed: module field_collection
```sh
Check all subsites : drush sqlq "select filename from system where name='field_collection'"
Inform subsites using it they should add it to their custom folder
drush rr 
drush cc all
```

NEPT-226: Remove field_collection from core.

---

resources/multisite_drupal_standard.make

Upgrade i18n module, remove a patch.
- Changed: i18n module version
```sh
no command
```

NEPT-392: Upgrade i18n, remove patch.

---

resources/multisite_drupal_standard.make

Upgrade diff module to latest commit.
- Changed: Version of DIFF module.
```sh
no command
```

NEPT-267: Upgrade diff module to latest commit.

---

profiles/common/modules/features/nexteuropa_feature_set/multisite_drupal_features_set_standard/multisite_drupal_features_set_standard.info

Feature sets: documentation index is unset when empty.
- Added: Documentation links to the feature sets array.

NEPT-1538: Feature sets: documentation index is unset when empty.

---

profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/src/DgtRulesTools.php

Fix for the DGT Fast Track Translations feature
- Changed: profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/src/DgtRulesTools.php
No commands are needed.

NEPT-1533: Hot Fix for the DGT FTT feature - support 2.3

---

profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/src/DgtRulesTools.php

Fix for the DGT Fast Track Translations feature
- Changed: profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/src/DgtRulesTools.php
No commands are needed.

NEPT-1533: Hot Fix for the DGT FTT feature.

---

profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/src/DgtRulesTools.php
profiles/common/modules/features/nexteuropa_feature_set/multisite_drupal_features_set_standard/multisite_drupal_features_set_standard.info
resources/multisite_drupal_standard.make

Fix Buges reported by QA team, hotfix on DGT Fast track.
- Fixed:  ne_dgt_rules/src/DgtRulesTools.php file, empty strings in feature sets documentation arrays, file_entity module version no longer pointing to commit nr

NEPT-1538, NEPT-1640, NEPT-1533: Several fixes for Fasttrack and QA.

---

resources/multisite_drupal_standard.make

Upgrade mimemail module to stable release.
- Changed: Upgrade mimemail to stable release.
```sh
no commands
```

NEPT-275: Upgrade mimemail module to stable release.

---

resources/multisite_drupal_standard.make

QA feedback, upgrade module and fix wrong way to include file in the module.
- Changed: administration_language_negotiation version upgraded to 2.4

NEPT-1506: QA feedback, upgrade module and fix nr2923727.

---

resources/multisite_drupal_standard.make

Add a patch to prevent errors when there is no link to delete
- Added: Patch #1824704

NEPT-1631: OM_maximenu add a patch to prevent errors when there is no link to delete

---

profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/rules/ne_dgt_rules_actions.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/ne_tmgmt_dgt_ftt_translator.install
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/ne_tmgmt_dgt_ftt_translator.module
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/TMGMTDefaultTranslatorPluginController/TmgmtDgtFttTranslatorPluginController.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/Tools/DataProcessor.php

Implementation of a new counter logic for the DGT Fast Track Feature.
- Changed: modules: ne_dgt_rules, ne_tmgmt_dgt_ftt_translator
No commands are for seen to make this change work.

NEPT-1661: DGT FTT Feature - new counter logic back ported from master.

---

profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/rules/ne_dgt_rules_actions.inc

Added optional language parameter to FTT rules.
- Added: Added optional language parameter to FTT rules.

NEPT-1562: Added language parameter to request translation action.

---

profiles/common/modules/features/multisite_wysiwyg/multisite_wysiwyg.module

Fix notice error, make sure the specific key exist prior doing array_merge().

NEPT-1621: Fix notice error, make sure the specific key exist prior doing array_merge().

---

build.package.xml
build.properties.dist
profiles/common/modules/custom/language_selector_site/language_selector_site.module
profiles/common/modules/custom/nexteuropa_ecl_migrate/nexteuropa_ecl_migrate.module
resources/multisite_drupal_standard.make

NEPT-1617: Review and cleanup component. - Part of the second meeting of the 16 November 2017.

NEPT-1617: Review and cleanup component. - Part 2.

---

profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/rules/ne_dgt_rules_actions.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/src/DgtRulesTools.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/TMGMTDefaultSubscriber/TmgmtDgtFttSubscriber.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/TMGMTDefaultTranslatorPluginController/TmgmtDgtFttTranslatorPluginController.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/Tools/DataProcessor.php
resources/composer.json
tests/features/tmgmt/fast-track.feature
tests/features/tmgmt/fast-track_custom-delay.feature
tests/features/tmgmt/fast-track_language-selection.feature
tests/src/Context/DrupalContext.php
tests/src/Context/MultilingualContext.php

Merge fast track functionalities in NEPT-1590, NEPT-1562, NEPT-1589 and NEPT-1588.
- Added: Added the possibility to customize the variable 'WorkflowCode' into the action + behat test.
- Added: Checking the translator type to correct dispatch upcoming translations.
- Added: Language parameter to request translation action.
- Added: Delay field + behat test.

NEPT-1591: Merge fast track functionalities from master

---

profiles/common/modules/custom/nexteuropa_token/modules/nexteuropa_token_ckeditor/plugins/nexteuropa_token_ckeditor/plugin.js
profiles/common/modules/features/multisite_wysiwyg/multisite_wysiwyg.behat.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/rules/ne_dgt_rules_actions.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/src/DgtRulesTools.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/TMGMTDefaultSubscriber/TmgmtDgtFttSubscriber.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/TMGMTDefaultTranslatorPluginController/TmgmtDgtFttTranslatorPluginController.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/Tools/DataProcessor.php
resources/composer.json
tests/features/nexteuropa_token/content_type_and_tokens.feature
tests/features/tmgmt/fast-track.feature
tests/features/tmgmt/fast-track_custom-delay.feature
tests/features/tmgmt/fast-track_language-selection.feature
tests/src/Context/ContextUtil.php
tests/src/Context/DrupalContext.php
tests/src/Context/MinkContext.php
tests/src/Context/MultilingualContext.php

merge of master into 2.5 + conflict resolution + Code sniffer fix.

Nept 1044 merge master 2.5 2

---

profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/README.md
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/src/Entity/CartBundle.php
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/src/Entity/CartItem.php
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/tmgmt_dgt_connector_cart.install
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/tmgmt_dgt_connector_cart.module

Allow to select languages when adding content to the cart
- Added:  Allow to select languages when adding content to the cart

Nept-1665:  Allow to select languages when adding content to the cart

---

resources/multisite_drupal_standard.make

NEPT-1159: merge master 2.5

---

resources/multisite_drupal_standard.make

NEPT-1159: Fix merge

---

resources/multisite_drupal_standard.make

NEPT-1159: Merge from master into release-2.5

---

resources/multisite_drupal_standard.make

Updated migrate module to version 7.x-2.8+19-dev & add patch for PHP7
- Changed: Update migrate module to latest version

NEPT-274: Updated migrate module to version 7.x-2.8+19-dev & add patch.

---

resources/multisite_drupal_standard.make

Add a patch that fix the entityreference language regression.
- Added: Patch 2850416

NEPT-1750: Add a patch that fix the entityreference language regression.

---

profiles/common/modules/custom/multisite_drupal_language_negociation/multisite_drupal_language_negociation.module
resources/multisite_drupal_standard.make

Merge of NEPT-1323, NEPT-1750 and NEPT-1753 into release-2.5

Upgrade metatag module version 1.21 to 1.22 (#1830)

---

profiles/common/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.install
resources/multisite_drupal_standard.make

Fix issues that blocks the build in release-2.5
- Changed: Fix CS in multisite_drupal_toolbox.install
- Removed: The useless patch: rendered_entity_is_not_language_aware_again-2850416-3.patch
No command needed.

NEPT-1761: Fix building issues on release-2.5

---

resources/multisite_drupal_standard.make

Update CHOSEN module to stable release 2.1 
- Changed:
multisite_drupal_standard.make

NEPT-155: Update CHOSEN module to stable release 2.1 .

---

tests/behat.yml.dist
tests/features/bootstrap/FeatureContext.php
tests/features/change_tracking_workflow.feature
tests/src/Extensions/DrupalExtension.php

Fixed failing wip test.
- Fixed: Fixed failing wip test.

NEPT-1213: Europa Theme break the Tracked changes feature

---

resources/multisite_drupal_standard.make

Upgrade version of module feeds_tamper.
- Changed: Version of module feeds_tamper.

NEPT-269: Upgrade version of module feeds_tamper.

---

tests/features/security/xss_vulnerability.feature

Resolve issues with phantomjs and Jenkins.
- Removed: the behat test for xss_vulnerability.feature
```sh
no commands
```

NEPT-master-jenkins: Add wip test unblocks phantomjs issues.

---

tests/features/security/xss_vulnerability.feature

Add wip test unblocks phantomjs issues.
- Fixed: Add wip test unblocks phantomjs issues.
```sh
no commands
```

NEPT-master-jenkins: Add wip test unblocks phantomjs issues. (#1869)

---

profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector.inc
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector.module
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/includes/forms/tmgmt_dgt_connector_form_cart_bundle_items.inc
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/includes/views/tmgmt_dgt_connector_cart.views_default.inc
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/src/Entity/CartItem.php
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/src/EntityViewsController/CartBundleViewsController.php
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/src/Metadata/CartItemMetadataController.php
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/src/ViewsHandler/CartBundleItemsCountDynamicField.php
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/tmgmt_dgt_connector_cart.install
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/tmgmt_dgt_connector_cart.module

Added character count information to entities and display options for views.
- Added: Added character count information to entities and display options for views.

NEPT-1768: Added character count property and logic.

---

profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/plugins/tmgmt_poetry.ui.inc

Update poetry plugin file to show correct info on detail of the job sent to translation.
- Changed:
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/plugins/tmgmt_poetry.ui.inc

NEPT-1643: Update poetry plugin file to show correct info.

---

profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/plugins/tmgmt_poetry.ui.inc

Merge from 2.4:
* NEPT-1643: Update poetry plugin file to show correct info.
* NEPT-1643: Improve code to avoid undefined index notice message.
- Changed:

NEPT-1643: Update poetry plugin file to show correct info. (#1829)

---

profiles/common/modules/features/nexteuropa_dgt_connector/README.md

Update documentation to not use the user Poetry in tests.
- Changed: Update documentation to not use the user Poetry in tests.
```sh
no command
```

NEPT-1737: Update documentation to not use the user Poetry in tests.

---

resources/multisite_drupal_standard.make

Upgrade media to 2.16.
- Changed: multisite_drupal_standard.make, media definition.
No command to do

NEPT-1321: Upgrade media to 2.16.

---

resources/multisite_drupal_standard.make

Upgrade module advagg to version 7.x-2.30
- Changed:
Version 2.17 to 2.30
drush updb

NEPT-499 Upgrade module advagg to version 7.x-2.21

---

profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/README.md
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/rules/ne_dgt_rules_actions.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/rules/ne_dgt_rules_conditions.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/src/DgtRulesTools.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/README.md
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/ne_tmgmt_dgt_ftt_translator.info
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/rules/ne_tmgmt_dgt_ftt_translator_rules.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/TMGMTDefaultSubscriber/TmgmtDgtFttSubscriber.php
tests/features/tmgmt/fast-track-opc.feature
tests/features/tmgmt/fast-track.feature
tests/features/tmgmt/fast-track_custom-delay.feature
tests/features/tmgmt/fast-track_language-selection.feature
tests/src/Context/PoetryContext.php

Create new rule condition and do updates for DGT Fast Track OPC workflow
- Added: Event documentation
- Added: Rules module dependency
- Changed: Translation Request event
- Changed: New rule condition
No commands are needed

NEPT-1836: [DGT Fast Track] New rule condition and updates for OPC workflow

---

.github/PULL_REQUEST_TEMPLATE.md

NEPT-1729: Update of the PR template

---

.github/PULL_REQUEST_TEMPLATE.md
build.properties.dist
build.test.xml
profiles/common/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.module
profiles/common/modules/custom/nexteuropa_ecl_migrate/nexteuropa_ecl_migrate.module
profiles/common/modules/features/multisite_workbench_moderation_view/multisite_workbench_moderation_view_alter.inc
profiles/common/modules/features/nexteuropa_dgt_connector/README.md
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/README.md
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/rules/ne_dgt_rules_actions.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/rules/ne_dgt_rules_conditions.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/src/DgtRulesTools.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/README.md
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/ne_tmgmt_dgt_ftt_translator.info
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/rules/ne_tmgmt_dgt_ftt_translator_rules.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/TMGMTDefaultSubscriber/TmgmtDgtFttSubscriber.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/TMGMTDefaultTranslatorPluginController/TmgmtDgtFttTranslatorPluginController.php
profiles/multisite_drupal_communities/multisite_drupal_communities.info
profiles/multisite_drupal_standard/multisite_drupal_standard.info
resources/drupal-core.make
resources/multisite_drupal_standard.make
tests/features/page_layout.feature
tests/features/subscriptions.feature
tests/features/tmgmt/fast-track-opc.feature
tests/features/tmgmt/fast-track.feature
tests/features/tmgmt/fast-track_custom-delay.feature
tests/features/tmgmt/fast-track_language-selection.feature

Merge of the "master" commits covering the ticket NEPT-1836 but also NEPT-1849, NEPT-1344, NEPT-1835, NEPT-1737, NEPT-1422, NEPT-1430, NEPT-1729, NEPT-864, NEPT-308, into release-2.5.

NEPT-1836: Merge from master to 2.5

---

build.properties.dist
build.test.xml
profiles/common/modules/custom/language_selector_site/language_selector_site.module
profiles/common/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.module
profiles/common/modules/custom/nexteuropa_ecl_migrate/nexteuropa_ecl_migrate.module
profiles/common/modules/features/multisite_workbench_moderation_view/multisite_workbench_moderation_view_alter.inc
profiles/common/modules/features/nexteuropa_dgt_connector/README.md
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/README.md
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/rules/ne_dgt_rules_actions.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/rules/ne_dgt_rules_conditions.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_dgt_rules/src/DgtRulesTools.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/README.md
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/ne_tmgmt_dgt_ftt_translator.info
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/rules/ne_tmgmt_dgt_ftt_translator_rules.inc
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/TMGMTDefaultSubscriber/TmgmtDgtFttSubscriber.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/TMGMTDefaultTranslatorPluginController/TmgmtDgtFttTranslatorPluginController.php
profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.module
profiles/multisite_drupal_communities/multisite_drupal_communities.info
profiles/multisite_drupal_standard/multisite_drupal_standard.info
resources/drupal-core.make
resources/multisite_drupal_standard.make
tests/features/page_layout.feature
tests/features/subscriptions.feature
tests/features/tmgmt/fast-track-opc.feature
tests/features/tmgmt/fast-track.feature
tests/features/tmgmt/fast-track_custom-delay.feature
tests/features/tmgmt/fast-track_language-selection.feature
tests/src/Context/PoetryContext.php

Upgrade Drupal to 7.57
- Added:
- Changed: drupal-core.make, the version of Drupal

NEPT-1849: Merge from master into 2.5

---

resources/multisite_drupal_standard.make

Upgrade menu attributes module to 1.0

Menu attibutes module upgraded to 1.0

---

profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector.inc
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector.module
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/tmgmt_dgt_connector_cart.install
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/tmgmt_dgt_connector_cart.module
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/tmgmt_poetry.module

Added support to send any type of item. Added option to send block items.
- Changed: Added support to send any type of item. Added option to send block items.

NEPT-1857: Added support for any type of item.

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.helpers.inc
resources/multisite_drupal_standard.make

Update uuid module to v 1.0
Code Sniff fix for cce_basic_config.helpers.inc

NEPT-1327: Update uuid module to v 1.0

---

resources/multisite_drupal_standard.make

Upgrade Entity API to the version 7.x-1.9
- Changed:
resources/multisite_drupal_standard.make

NEPT-1842 : Upgrade Entity API to the version 7.x-1.9

---

tests/behat.yml.dist
tests/features/tmgmt/tmgmt_dgt_connector.feature
tests/features/tmgmt/tmgmt_dgt_connector_cart.feature

Added tests for vocabularies and taxonomies
- Added: Tests for translating vocabularies and taxonomies.

NEPT-1867: Added tests for vocabularies and taxonomy terms.

---

resources/multisite_drupal_standard.make

NEPT-1328: Upgrade video module to 7.x-2.13

---

profiles/common/modules/custom/ecas/includes/ecas.inc
resources/multisite_drupal_standard.make

Upgrade autologout to 7.x-4.5.
- Changed: resources/multisite_drupal_standard.make to change the version of autologout.
None

NEPT-1901: Upgrade autologout to 7.x-4.5

---

resources/multisite_drupal_standard.make

Remove jqmulti from platform.
- Removed: Remove jqmulti from platform.

NEPT-1493: Remove jqmulti from platform.

---

profiles/common/modules/features/multisite_wysiwyg/multisite_wysiwyg.behat.inc
resources/multisite_drupal_standard.make

Remove jqmulti from platform.
- Removed: Remove jqmulti from platform.

NEPT-1493: Remove jqmulti from platform. (#1972)

---

resources/multisite_drupal_standard.make

Upgrade ds to 2.15.
- Changed: make file for upgrading 2.15
None

NEPT-1923: Upgrade ds to 2.15.

---

resources/multisite_drupal_standard.make

Upgrade ds to 2.15.
- Changed: make file for upgrading 2.15
None

NEPT-1923: Upgrade ds to 2.15

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.install
profiles/common/modules/features/nexteuropa_trackedchanges/nexteuropa_trackedchanges.module

Add ckeditor to filtered format.
- Added: Add ckeditor to filtered format.

NEPT-1593: Add ckeditor to filtered format.

---

profiles/multisite_drupal_communities/modules/custom/multisite_dynamic_basetheme
profiles/multisite_drupal_standard/modules/custom/multisite_dynamic_basetheme

Remove useless symlinks.
- Removed: Useless symlinks.
no commands

NEPT-1931: Remove useless symlinks.

---

resources/multisite_drupal_standard.make

Update Atomium version from 2.7 to 2.8.

NEPT-1909: Update Atomium version from 2.7 to 2.8.

---

resources/multisite_drupal_standard.make

Security update Media module SA-CONTRIB-2018-020
- Security: Patch Media module for SA-CONTRIB-2018-020
drush cc all

NEPT-1935: Upgrade Media module to 7.x-2.19

---

resources/multisite_drupal_standard.make

Security update Media module SA-CONTRIB-2018-020
- Security: Patch Media module for SA-CONTRIB-2018-020
No command

NEPT-1935: Patch Media module

---

build.properties.dist
resources/multisite_drupal_standard.make

Update the ec_europa theme to 0.0.11.
- Changed: version of ec_europa to 0.0.11
no-commands

NEPT-1907: Update the ec_europa theme to 0.0.11.

---

build.properties.dist
resources/multisite_drupal_standard.make

Update EC_EUROPA 0.0.11
- Changed: version of ec_europa.
no-commands

NEPT-1907: Update EC_EUROPA 0.0.11

---

profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector.inc
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/tmgmt_dgt_connector_cart.install
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/tmgmt_dgt_connector_cart.module
tests/features/tmgmt/tmgmt_dgt_connector_cart.feature

Added language selector to all source pages.
- Added: Added language selector to all source pages.

NEPT-1862: Added language selector to all source pages.

---

profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/tmgmt_dgt_connector_cart.module
tests/features/tmgmt/tmgmt_dgt_connector_cart.feature

Add location to locale items added to a cart.
- Added: Add location to locale items added to a cart.

NEPT-1911: Add location to locale items added to a cart.

---

tests/features/tmgmt/tmgmt_dgt_connector_cart.feature

Ensure Metatags can be sent to DGT. Create Behat test.
- Added: Behat test
No commands are needed.

NEPT-1868: [Small jobs] Ensure Metatags can be sent to DGT

---

profiles/common/modules/features/multisite_settings/multisite_settings_core/multisite_settings_core.strongarm.inc
resources/multisite_drupal_standard.make

* NEPT-1844: Fix plupload ajax not uploading files properly. (#1996)
* NEPT-1770: Removed theme_default variable. (#1968)
- Fixed:  Fix plupload ajax not uploading files properly. 
- Removed: Removed theme_default variable.

NEPT-1844 & NEPT-1770

---

profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.module
resources/multisite_drupal_standard.make

* NEPT-978: Added the piwik script to maintenance pages.
* NEPT-978: Add the _nexteuropa_piwik_add_load_js_to_page() function and the related logic.
* NEPT-1928: Use the official release of nexxteuropa_newsroom

NEPT-978: Added the piwik script to maintenance pages

---

profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.info
profiles/common/modules/features/nexteuropa_webtools/nexteuropa_webtools.info
resources/multisite_drupal_standard.make
tests/behat.yml.dist
tests/features/change_tracking_workflow.feature
tests/features/editorial_workflow.feature
tests/features/nexteuropa_token/block_type_and_tokens.feature
tests/features/piwik.feature
tests/features/webtools.feature
tests/src/Context/MinkContext.php
tests/src/Context/ModuleContext.php

Fix permissions assigned to content created when using the moduel workbench_og
Add nexteuropa_metatags dependency to webtools and piwik
- Added: Add patch to fix node permisions
- Added: Add nexteuropa_metatags dependency to webtools and behat test
- Changed: Change the version installed of the workbench_og module
- Changed: Replace behat step filling the title field by a specific step pointing explicitly the content title.
[Insert commands here]

NEPT-1866: JRC: Contributor to see own drafts under "Manage Content"/"My drafts" workbench tab

---

resources/multisite_drupal_standard.make

Change the reference patch of the workbench moderation issue #2825391
- Changed: patch URL in rresources/multisite_drupal_standard.make
drush cc all

NEPT-1922: Change the reference 2825391 patch of workbench_moderation for 46

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.helpers.inc

Fixed the issue with previous emoji check which was firing up some ASCII symbol.
- Fixed:
The code that was checking for emojis.
NA

NEPT-1936: Allow some emojis that were blocked before

---

resources/multisite_drupal_standard.make

Update file_entity module to 2.21
- Changed: Update file_entity module to 2.21

NEPT-1644: Update file_entity module.

---

profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.module

Add defer attribute on the piwik smartloader script tag in the nexteuropa_piwik module
- Changed: nexteuropa_piwik.module: Add defer option to smarloader js file.
drush cc all

NEPT-1894: Add defer attribute on the piwik smartloader script tag

---

profiles/common/modules/features/multisite_wysiwyg/multisite_wysiwyg.module

Use theme machine names instead of themes regular human name.

NEPT-1980: Use theme machine names instead of themes regular human name.

---

resources/multisite_drupal_standard.make

Update themes EC Europa and Atomium.
**drush cc all required**

NEPT-1991: Update themes EC Europa and Atomium

---

resources/multisite_drupal_standard.make

Increase size of redirect urls to 900.
- Changed:  Increase size of redirect urls to 900.

NEPT-1943: Increase size of redirect urls to 900.

---

resources/multisite_drupal_standard.make

Update jplayer module.
- Changed: Update jplayer module.

NEPT-1657: Update jplayer module.

---

resources/multisite_drupal_standard.make

Upgrade Select (or other) module to 2.24
- Changed: resources/multisite_drupal_standard.make, upgrade the module version.
drush cc all

NEPT-2033: Upgrade Select (or other) module to 2.24

---

resources/multisite_drupal_standard.make

* NEPT-2005: Upgrade entity_translation.
* NEPT-2005: Add patch for workbench moderation and entity translation integration.
* NEPT-2005: Add new patch reroll.

NEPT-2005: Upgrade entity_translation. (#2121)

---

resources/multisite_drupal_standard.make

Upgrade link module to version 1.5
- Changed: resources/multisite_drupal_standard.make
drush updatedb

NEPT-2008: Upgrade link module to the latest version

---

profiles/common/modules/custom/tmgmt_workbench/README.txt

Remove outdated readme file
- Removed: readme of the cusomt tmgmt_workbench module

NEPT-788: Remove outdated readme file

---

Jenkinsfile
build.properties.dist
build.test.xml
resources/multisite_drupal_standard.make
tests/behat.yml.dist
tests/features/bootstrap/FeatureContext.php
tests/features/nexteuropa_token/handling_invalid_wysiwyg_token.feature
tests/src/Context/CKEditorContext.php
tests/src/Context/DrupalContext.php
tests/src/Context/TokenContext.php

Add a test on URL tokens
Upgrade UUID
Save screenshot when test fails
Upgrade views_bulk_operations module to version 7.x-3.5
Upgrade print to 2.2.
- Added: Behat test on url tokens
- Changed : 
- resources/multisite_drupal_standard.make to upgrade the version of UUID
- resources/multisite_drupal_standard.make to upgrade the print module version.
- resources/multisite_drupal_standard.make to upgrade the version of views_bulk_operations to 3.5

Release 2.5

---

resources/multisite_drupal_standard.make

Update TMGMT patch for better control of translated data length
- Changed: TMGMT patch

NEPT-2029: Update TMGMT patch for better control of translated data length

---

resources/multisite_drupal_standard.make

Mimemail module upgraded to v1.1
- Changed: resources/multisite_drupal_standard.make
drush cc all

NEPT-2107: Mimemail module upgraded to v1.1
