ec-europa/platform-dev

resources/multisite_drupal_standard.make

1. Upgrade workbench_email from 3.4 to 3.5
2. Apply patch from https://www.drupal.org/node/2501321 as requested in https://webgate.ec.europa.eu/CITnet/jira/browse/MULTISITE-7225
The patch is applied despite the maintainer's  comment (workbench_email.features.inc at Line 60)
// Message / Subject are not outputted. Since they are text values
// and could change once pushed to production environment. Meaning
// feature would remain in an overridden state.

workbench_email upgrade and patch

---

resources/multisite_drupal_standard.make

Also replaced patches/fullcalendar-ajax_date_format-2185449-11.patch with the drupal org version.

MULTISITE-7373 - Issue #2325549: AJAX doesn't work in jQuery 1.9+

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.strongarm.inc

Right now, the cce_basic_config sets the "Alternate jQuery version for administrative pages" to 1.5. This is not compatible with the "add media" button from CKeditor. It should be at least 1.7

bugfix/MULTISITE-7351 - admin jquery minimum version

---

.travis.yml

Once merged to develop, it will generate a package from the build folder when a new tag is pushed ( so after testing by cphp ) and publish it to the github releases page.
eg : https://github.com/ec-europa/platform-dev/releases/download/2.1.6/next-europa-platform-2.1.6.tar.gz

Use travis to release builds on github

---

profiles/common/modules/features/multisite_settings/multisite_settings_core/multisite_settings_core.install

to fix "Fatal error: Call to undefined function language_types_set()"

NEXTEUROPA-6837: include language.inc in hook_update

---

profiles/common/modules/custom/multisite_drupal_language_negociation/multisite_drupal_language_negociation.install
profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.install
tests/features/bootstrap/FeatureContext.php
tests/features/splash_screen.feature

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-5585

NEXTEUROPA-5585: Splash screen: Link to language versions does not work if language uses a custom prefix

---

resources/multisite_drupal_standard.make

Requested by customer developers to have a fixed/locked version of geophp 1.x-dev (IT IS A DEV VERSION). This module needs to be glued to a commit.

MULTISITE-7873-geophp-lockdown

---

profiles/common/themes/ec_resp/ec_resp.info

```php = "5.2.4"```
This defines the minimum PHP version the theme will support but there were reports of not able to install the platform because the code uses new PHP syntax.
The line that produces the error is:
```
$form['search_input_group']['europa_search_submit']['#attributes']['class'] = array_merge(['search_input_group']['europa_search_submit']['#attributes']['class'], array('btn', 'btn-default'));
```

MULTISITE-8283-version-fix

---

profiles/multisite_drupal_communities/modules/custom/multisite_drupal_access/multisite_drupal_access.module

- lower priority of custom realm
- use workbench revision status instead of default node status

NEXTEUROPA-8289: node access in community profile

---

resources/multisite_drupal_standard.make

Following some refactoring due to NEXTEUROPA-9865, the platform-theme has been updated to 0.2.0

NEXTEUROPA-9865: Update platform-theme's link and version

---

profiles/common/modules/custom/multisite_og_navigation_tree/multisite_og_navigation_tree.taxonomy.inc

Fix PHP notice and warning on the taxonomy term delete form.
Error:
Notice: Undefined index: relations in
_mont_group_taxonomy_edit_term() (line 50 of
/ec/dev/server/fpfis/webroot/sources/gervase/repositories/subsites/heli-dev/platform/profiles/common/modules/custom/multisite_og_navigation_tree/multisite_og_navigation_tree.taxonomy.inc).
Warning: Invalid argument supplied for foreach() in
_mont_group_taxonomy_edit_term() (line 52 of
/ec/dev/server/fpfis/webroot/sources/gervase/repositories/subsites/heli-dev/platform/profiles/common/modules/custom/multisite_og_navigation_tree/multisite_og_navigation_tree.taxonomy.inc).

multisite_og_navigation_tree: fix php warning

---

profiles/common/modules/custom/nexteuropa_laco/src/LanguageCoverageService.php

https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-9797

NEXTEUROPA-9797: Avoid using drupal_exit() in hook_boot() context.

---

profiles/common/modules/custom/language_selector_page/language_selector_page.info

This dependency is needed because the starterkit (altered for nems) fails on "install-dev" because of a missing dependency: https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-12350

Added dependency on multisite_drupal_toolbox

---

profiles/common/modules/custom/multisite_config/lib/Drupal/filter/Config.php
profiles/common/modules/features/cce_basic_config/cce_basic_config.install
profiles/common/modules/features/multisite_wysiwyg/includes/multisite_wysiwyg.settings.inc
profiles/common/modules/features/multisite_wysiwyg/multisite_wysiwyg.behat.inc
profiles/common/modules/features/multisite_wysiwyg/multisite_wysiwyg.module
profiles/common/modules/features/nexteuropa_core/nexteuropa_core.module
tests/features/multisite_wysiwyg/multisite_wysiwyg_settings_check.feature

Following description comes from #751:
PR includes following elements:
- new text format - Full HTML + Change trackng
- new WYSIWYG profile cloned from Full HTML
- new admin page for the multisite_wysiwyg module
- enabling/disabling change tracking plugin for create and edit content pages
- enabling/disabling change tracking plugin for given WYSIWYG profile
- provides information table regarding status of change tracking plugin for available WYSIWYG profiles
To use on existing sites you need to configure settings on `admin/config/content/multisite_wysiwyg/setup`
For new sites webmaster would be able to select profile with change tracking if needed. To set up behaviour on create/edit content pages you need to configure settings on `admin/config/content/multisite_wysiwyg/setup`

NEXTEUROPA-12123: Wysiwyg: track changes incorrect behaviour

---

phpcs-ruleset.xml
resources/multisite_drupal_standard.make

Balasz will move the repo code on the root as for the moment the download will be on a 'newsroom' folder.
=>expected location once this is done profiles/multisite_drupal_standard/modules/custom/nexteuropa_newsroom

NEXTEUROPA-12782 Include nexteuropa newsroom folder in the make file

---

README.md

As travis-ci is not used anymore, keeping the status label is confusing and will not show the real status of the last build.

remove travis-ci status label

---

profiles/common/themes/ec_resp/templates/blocks/block.tpl.php
resources/drupal-core.make

This PR fixes two things:
1. The missing tag `$attributes`,
2. The missing comments in many templates in Drupal. See [#569362](https://www.drupal.org/node/569362). I've uploaded a patch upstream, and included in makefile.
You need to flush cache to get this working properly.
Internal issue link: https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-64

NEPT-64: ec-resp / block.tpl.php - missing tag $attributes.

---

resources/multisite_drupal_standard.make

Some Views do not provide sufficient access check, which is considered as security risk , as it may allow to expose the view information to the unwanted user.
This PR fix the problem by adding an upstream patch to the makefile.
Link to the drupal.org issue: https://www.drupal.org/node/2812863
JIRA Link: https://webgate.ec.europa.eu/CITnet/jira/browse/NEPT-60

NEPT-60: TMGMT: Fix insufficient access check on Views.

---

profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.tokens.inc

The token "**node:entity-translation-languages**" and the variable "**nexteuropa_multilingual_warning_message_languages**" will be removed from code. But maybe they are currently being used in custom code in some subsites.
The removal of the variable should not cause any problem, because it will still exist in the database (**no** hook_update_N with variable_del() is created).
But the removal of the token will make the token not to be replaced. This is not a critical error, but still if possible in the QA process by the maintenance team, some evaluation of the uses of this token in subsites can have place. If considered too risky, we can reconsider the removal of this token.

fix(multilingual): fix error when content has language UND

---

resources/multisite_drupal_standard.make

Actually the drush make workflow automatically apply patches to projects.
In some cases, it wont work properly due to some version of the git and patch softwares.
This patch fix the problem by using the right standard patch that works everywhere.
Please read more information here: https://www.drupal.org/node/1903850
This is a blocker and this should go to master as the changes in the code are not impacting anything.
FYI, [here a link that](http://pastebin.com/wWLLXUfg) shows the diff between the version currently used (1.7) and the version I would like to use.
Please, could you think about it twice?

NEPT-310: Patch plupload with a format valid git patch.

---

tests/behat.api.yml.dist
tests/behat.i18n.yml.dist
tests/src/Context/MultilingualContext.php

Move context from nexteuropa_multilingual.behat.inc into tests/src/Context 
This fixes "Trait 'Drupal\nexteuropa\Context\ContextUtil' not found" error in subsites.

NEPT-552: fix(maintenance): Move context from nexteuropa_multilingual into tests/src/Context - NEPT-552

---

profiles/multisite_drupal_communities/modules/custom/multisite_drupal_features_set_standard
profiles/multisite_drupal_communities/modules/custom/nexteuropa_ds_layouts
profiles/multisite_drupal_communities/modules/custom/nexteuropa_formatters
profiles/multisite_drupal_communities/modules/custom/tmgmt_dgt_html
profiles/multisite_drupal_communities/modules/custom/tmgmt_poetry
profiles/multisite_drupal_communities/modules/features/multisite_review
profiles/multisite_drupal_communities/modules/features/nexteuropa_dgt_connector
profiles/multisite_drupal_communities/modules/features/nexteuropa_event
profiles/multisite_drupal_communities/modules/features/nexteuropa_faq
profiles/multisite_drupal_communities/modules/features/nexteuropa_feature_set
profiles/multisite_drupal_communities/modules/features/nexteuropa_geofield
profiles/multisite_drupal_communities/modules/features/nexteuropa_mediagallery
profiles/multisite_drupal_communities/modules/features/nexteuropa_news
profiles/multisite_drupal_communities/modules/features/nexteuropa_trackedchanges

During the deployment of the 2.3 release on the test environment, DevOps team encountered on an issue with some missing and broken symlinks which are not aligned between the standard and community profiles.
Test deployment for the release 2.3 was introduced and needed for the NEPT-375.
As this fact is blocking the test of deployment process for the major 2.3 release after discussed with the Community, DevOps and Core team we decided to create this ticket.
To unblock the deployment process DevOps team asked for performing alignment of the symlinks between profiles.
Pull request included in issue needs to have at least one 👍 from the Community Team member.
CC: @Fefaine @jfhovinne @champcy @gervasek

NEPT-618: Aligning symlinks between standard and community profile

---

phpcs-ruleset.xml
profiles/common/modules/custom/nexteuropa_piwik/README.md
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.admin.inc
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.info
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.install
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.module
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.rule.admin.inc
profiles/common/modules/custom/nexteuropa_piwik/src/Entity/PiwikRule.php
profiles/common/modules/custom/nexteuropa_piwik/src/EntityDefaultUIController/PiwikRuleEntityUIController.php
tests/behat.yml.dist
tests/features/piwik.feature
tests/src/Context/PiwikRulesContext.php

Clone of the **PR #1259** which have been merged with the support-2.2 branch.
List of squashed commits:
* NEPT-717: Advanced PIWIK rules feature
* NEPT-717: Appling the code review suggestions
* NEPT-717: Another part of code review suggestions
* NEPT-717: Another portion of Code Review suggestions
* NEPT-717: Disabling piwik.feature as it has problems with the currently implemented way of cleaning DB in the after scenario step
* NEPT-717: Filling the missing parts of the documentation
* NEPT-717: Stabilizing and implementing the code review suggestions
* NEPT-717: Extending 'Remove a Piwik rule' scenario
* NEPT-717 - Add an extra check that the removed rule does not show
* NEPT-717: Made small remarks on Readme and removed permission from administrators

NEPT-717: Advanced PIWIK rules feature - master

---

phpcs-ruleset.xml
profiles/common/modules/custom/nexteuropa_varnish/README.md
profiles/common/modules/custom/nexteuropa_varnish/includes/cache_purge_rule.ui.inc
profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.admin.inc
profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.install
profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.module
profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.rules.admin.inc
tests/features/frontend_cache_purge.feature
tests/src/Context/FrontendCacheContext.php

Clone of the PR #1282 to include it into the 2.4 branch
* NEPT-775: The default purge rule functionality
* NEPT-775: Fixing problem with the Behat tests + docs
* NEPT-775: Changing the order of steps in Behat scenarios
* NEPT-775: Changing the order of steps in Behat scenarios + case for new nodes without rules
* NEPT-775: Tweak the new node case
* NEPT-775: Extending default rule usage. Excluding new nodes, including translations.
* NEPT-775: Removing a case for sending purge request on the node creation
* NEPT-775: Stabilizing and implementing the code review suggestions
* NEPT-775: Implementing suggestions from the Code Review
* NEPT-744: Improved comment readability

NEPT-775: Invalidate the cache by default rule - 2.4

---

phpcs-ruleset.xml
profiles/common/modules/custom/nexteuropa_piwik/README.md
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.admin.inc
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.info
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.install
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.module
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.rule.admin.inc
profiles/common/modules/custom/nexteuropa_piwik/src/Entity/PiwikRule.php
profiles/common/modules/custom/nexteuropa_piwik/src/EntityDefaultUIController/PiwikRuleEntityUIController.php
tests/behat.yml.dist
tests/features/piwik.feature
tests/src/Context/PiwikRulesContext.php

Clone of the PR #1324 which have been merged with the master branch.
List of squashed commits:
NEPT-717: Advanced PIWIK rules feature
NEPT-717: Appling the code review suggestions
NEPT-717: Another part of code review suggestions
NEPT-717: Another portion of Code Review suggestions
NEPT-717: Disabling piwik.feature as it has problems with the currently implemented way of cleaning DB in the after scenario step
NEPT-717: Filling the missing parts of the documentation
NEPT-717: Stabilizing and implementing the code review suggestions
NEPT-717: Extending 'Remove a Piwik rule' scenario
NEPT-717 - Add an extra check that the removed rule does not show
NEPT-717: Made small remarks on Readme and removed permission from administrators

NEPT-717: Advanced PIWIK rules feature - 2.4

---

build.properties.dist
build.test.xml
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/tmgmt_poetry_mock/src/Mock/PoetryMock.php
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/tmgmt_poetry_mock/tmgmt_poetry_mock.behat.inc
tests/behat.yml.dist
tests/features/embedded_image.feature
tests/features/events.feature
tests/features/feature_set/nexteuropa_trackedchanges_set.feature
tests/features/maxlength.feature
tests/features/multilingual_admin.feature
tests/features/nexteuropa_communities.feature
tests/features/nexteuropa_token/block_type_and_tokens.feature
tests/features/pathauto.feature
tests/features/piwik.feature
tests/features/tmgmt/tmgmt_poetry_translations.feature
tests/src/Context/AgnosticBatchContext.php
tests/src/Context/ContentTypeContext.php
tests/src/Context/DrushContext.php
tests/src/Context/FieldContext.php
tests/src/Context/ModuleContext.php
tests/src/Context/PiwikRulesContext.php

Clone of the PR #1309 against the release-2.4 branch.
List of squashed commits:
* NEPT-831: New DrushContext + changes in the dist files
* NEPT-831: Adding clear all caches to BeforeFeature step
* NEPT-831: Removing clearing caches (no impact), putting @wip on pathauto.feature
* NEPt-831: Changing order in the background for failing tests
* NEPT-831: Tweaking configuration for the tmgmt_poetry_translations.feature
* NEPT-831: Remove the mock TMGMT translator in a tagged scenario
* NEPT-831: Cleanup the mock TMGMT translator in a tagged scenario
* NEPT-831: Putting '@wip' on the nexteuropa_trackedchanges_set.feature:9 scenario
* NEPT-831: Tweaks on the nexteuropa_trackedchanges_set.feature
* NEPT-831: Revert on the nexteuropa_trackedchanges_set.feature
* NEPT-831: Remove an useless …

NEPT-831: Cleaning the environment before running the Behat feature - 2.4

---

profiles/common/modules/features/communities/communities.install
profiles/common/modules/features/nexteuropa_communities/nexteuropa_communities.install

Prevent modules communities and nexteuropa_communities to be enabled
simultaneous
NEXTEUROPA-13955

NEXTEUROPA-13955: Add hook_requirement on communities features

---

profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.module

Quick fix to align with the trimmed purge paths which are expected by Varnish.

NEPT-1163: Removing the base path from the purge paths

---

profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.module

Removing base path part form the purge paths.
- Added: new trimming function for the purge paths
- Changed: functionality of collecting paths
No specific commands to execute

NEPT-1163: nexteuropa_varnish - unable to use cache invalidation

---

tests/behat.yml.dist
tests/features/scheduler.feature
tests/src/Context/SchedulerContext.php

Scheduler Workbench doesn't change the state of a node on cron run
- Fixed:
Scheduler Workbench doesn't change the state of a node on cron run
```sh
No additional commands needed
```

Master into release 2.4

---

Jenkinsfile

Use withEnv step in the pipeline to override variables
- Fixed: communities profile was not tested correctly
No additional command needed.

NEPT-1187: use withEnv step to override variables

---

resources/drupal-core.make
resources/multisite_drupal_standard.make

Update Drupal Core to 7.56
- Removed: removed patch from MULTISITE-5641
- Security: Drupal Core 7.56
No specific command to execute.

NEPT-1185: Upgrade Drupal Core to 7.56 and disable patch

---

profiles/common/modules/features/multisite_wysiwyg/README.md
profiles/common/modules/features/multisite_wysiwyg/multisite_wysiwyg.module

Implement a namespace CSS class into the CKEditor widget to format the WYSIWYG content according the ECL style guide.
- Added: The mechanism referencing automatically the CSS file specific to the WYSIWYG widget
- Added: The "ecl-editor" CSS class into the "body" tag of the CKEditor flag to format the widget content according to the ECL style guide
```sh
drush cc all
```

NEPT-1171: Implement the components in WYSIWYG via custom stylesheet

---

profiles/common/modules/custom/ecas/includes/ecas.inc
profiles/common/modules/features/nexteuropa_core/nexteuropa_core.info
profiles/common/modules/features/nexteuropa_core/nexteuropa_core.install
profiles/common/modules/features/nexteuropa_core/nexteuropa_core.module
profiles/common/modules/features/nexteuropa_core/nexteuropa_core.strongarm.inc
resources/multisite_drupal_standard.make

Automaticaly logout user after inactivity.
Don't allow to use the same EU Login session after logout from Drupal.
- Added: Module [Autologout](https://www.drupal.org/project/autologout), always enabled;
- Added: Set variables for Autologout;
- Changed: Automaticaly logout user after inactivity (set to 30 minutes);
- Changed: ECAS login process will prevent reuse of same EU Login session after logout from Drupal.
```sh
$ drush updb
```

NEPT-859: Automaticaly logout user after inactivity

---

profiles/common/modules/features/nexteuropa_metatags/nexteuropa_metatags.helpers.inc

Locking default fieldsprovided by metatag feature.
- Changed: Metatag fields are locked.

NEPT-1268: Locked metatag files.

---

profiles/common/modules/custom/nexteuropa_lastupdate/README.md
profiles/common/modules/custom/nexteuropa_lastupdate/nexteuropa_lastupdate.module
tests/features/last_update.feature

Review nexteuropa_lastupdate:
Also I have doubts on the accuracy of this module. What if a block is placed on a menu item that takes more than one object in it's load functions.
Then you only load the first one you find? I'm aware of this issue because I've worked with the menu_token module that I've also tried to implement logic like this in. So at least I would document this modules behavior and provide a test for each implemented entity.
https://github.com/ec-europa/platform-dev/blob/2.4.0/profiles/common/modules/custom/nexteuropa_lastupdate/nexteuropa_lastupdate.module#L91
- Added: Behat test for last_update module to check user and file entities.
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
No commands
```

NEPT-1271: Add behat test for last_update module and update the readme.

---

profiles/common/modules/custom/nexteuropa_lastupdate/README.md
profiles/common/modules/custom/nexteuropa_lastupdate/nexteuropa_lastupdate.module
profiles/common/modules/custom/nexteuropa_lastupdate/theme/nexteuropa-last-update-block.tpl.php
profiles/common/modules/features/ec_embedded_video/ec_embedded_video.install
profiles/common/modules/features/ec_embedded_video/ec_embedded_video.install.inc
profiles/common/modules/features/nexteuropa_metatags/nexteuropa_metatags.helpers.inc
profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.install
profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.install.inc
tests/features/last_update.feature

Release 2.4: QA feedback application for blockers
Changed: NEPT-1271: Add behat test for last_update module and update the readme.
Changed: NEPT-1267: Move helper functions outside of install file.
Changed: NEPT-1268: Locked metatag files.
Changed: NEPT-1269: Move helper functions outside of install file.
Changed: NEPT-1270: Clean tpl for the nexteuropa_lastupdate module.
Changed: NEPT-1270: Refactor the preprocess method.
```sh
drush cc all
```

NEPT-1252: Release 2.4: QA feedback application for blockers

---

Jenkinsfile
README.md
build.package.xml
build.properties.dist
build.test.xml
phpcs-ruleset.xml
profiles/common/modules/custom/nexteuropa_ecl_migrate/nexteuropa_ecl_migrate.module
profiles/common/modules/features/cce_basic_config/cce_basic_config.context.inc
profiles/common/modules/features/cce_basic_config/cce_basic_config.install
profiles/common/modules/features/multisite_settings/multisite_settings_core/multisite_settings_core.strongarm.inc
profiles/common/modules/features/multisite_wysiwyg/multisite_wysiwyg.module
profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.install
profiles/multisite_drupal_communities/multisite_drupal_communities.install
profiles/multisite_drupal_standard/multisite_drupal_standard.install
resources/multisite_drupal_standard.make
tests/features/search/europa_search_ec_europa.feature

The scope of this PR is to allow theme to be set at installation time, both via UI or via Drush. This will allow CI to set which theme to use per build.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
[Insert commands here]
```

NEPT-1191: Stabilize theme: Create new phing target

---

resources/multisite_drupal_standard.make

Upgrade ec_resp to release 2.3.1
- Added: Maintenance offline page
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
no command
```

NEPT-1339: Upgrade ec_resp to 2.3.1.

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.install
resources/multisite_drupal_standard.make

NEPT-1429: Update variable for platform version.
NEPT-1339: Upgrade ec_resp to 2.3.1
- Added: hook_update_N in cce_basic_config to update the variable for platform version.
- Added: Maintenance offline page
```sh
drush updb
```

NEPT-1429: Update variable for platform version 2.4

---

resources/multisite_drupal_standard.make

Update the module ctools from 1.11 to last commit.
- Changed: Update the module ctools from 1.11 to last commit - 07/2017.
```sh
drush cc all
```

NEPT-411: Update the module ctools from 1.11 to latest commit.

---

resources/multisite_drupal_standard.make

Update views from 3.15 to 3.17 .
3.16 is a rather major bug fix release. It is strongly recommended to thoroughly test this release before uploading to production sites in case there are any regressions. There are two changes since 7.x-3.15 which affect how CSS classes are generated, so please pay particular attention to the themed output. Please report regressions immediately so that we can rectify them in a future release.
- Changed: Views version from 3.15 to 3.17
- Changed: Patches for views
No extra commands are required.

NEPT-1329: Update views to 3.17 - support-2.2

---

resources/multisite_drupal_standard.make

Update views from 3.15 to 3.17 .
3.16 is a rather major bug fix release. It is strongly recommended to thoroughly test this release before uploading to production sites in case there are any regressions. There are two changes since 7.x-3.15 which affect how CSS classes are generated, so please pay particular attention to the themed output. Please report regressions immediately so that we can rectify them in a future release.
- Changed: Views version from 3.15 to 3.17
- Changed: Patches for views
No extra commands are required.

NEPT-1329: Update views to 3.17 - support-2.3

---

resources/multisite_drupal_standard.make

Update views from 3.15 to 3.17 .
3.16 is a rather major bug fix release. It is strongly recommended to thoroughly test this release before uploading to production sites in case there are any regressions. There are two changes since 7.x-3.15 which affect how CSS classes are generated, so please pay particular attention to the themed output. Please report regressions immediately so that we can rectify them in a future release.
- Changed: Views version from 3.15 to 3.17
- Changed: Patches for views
No extra commands are required.

NEPT-1329: Update views to 3.17

---

resources/multisite_drupal_standard.make

Update views from 3.15 to 3.17 .
3.16 is a rather major bug fix release. It is strongly recommended to thoroughly test this release before uploading to production sites in case there are any regressions. There are two changes since 7.x-3.15 which affect how CSS classes are generated, so please pay particular attention to the themed output. Please report regressions immediately so that we can rectify them in a future release.
- Changed: Views version from 3.15 to 3.17
- Changed: Patches for views
No extra commands are required.

NEPT-1329: Merge from master into 2.5 - update views to 3.17 (#1527)

---

resources/multisite_drupal_standard.make

Update entityreference from a commit to the version 1.5.
- Added:Update entityreference from a commit to the version 1.5.
- Security: DRUPAL-SA-CONTRIB-2017-067
```sh
drush cc all
```

NEPT-1445: Update entityreference from a commit to the version 1.5.

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/multisite_block_carousel/multisite_block_carousel.module

Removed check plain on string literals in multisite_block_carousel delete link
- Changed: Removed check plain() on link title and replaced with t()

NEPT-1290: Remove check plain on string literals in multisite_block_carousel delete link

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/ecas/ecas.install
profiles/common/modules/custom/multisite_og_button/multisite_og_button.install
profiles/common/modules/features/f_a_q/f_a_q.install
profiles/common/modules/features/multisite_charts/multisite_charts.install
profiles/common/modules/features/multisite_crop_and_resize/multisite_crop_and_resize.install
profiles/common/modules/features/multisite_maps/multisite_maps.install
profiles/common/modules/features/nexteuropa_metatags/nexteuropa_metatags.install
profiles/common/modules/features/solr_config/solr_config.install

Replaced t() with get_t() in ecas, multisite_og_button, multisite_crop_and_resize, nexteuropa_metatags, f_a_q, multisite_charts, multisite_maps, solr_config
- Fixed: Replaced t() with get_t().

NEPT-1295: Replaced t() with get_t().

---

phpcs-qa-roadmap.xml

Remove the cs rule on a feature that is no longer part of the platform.
Remove the cs rule on a feature nexteuropa_subscriptions
- Removed: cs exception on nexteuropa_subscriptions
```sh
no commands
```

NEPT-1289: Remove the cs rule on a feature that is no longer part of the platform.

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/nexteuropa_laco/tests/LanguageCoverageServiceTest.php
profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.module

There must be one blank line after the last USE statement
- Changed: line spacing after use statement
```sh
no command
```

NEPT-1412: Fix QA automation rules - There must be one blank line after the last USE statement

---

Jenkinsfile
README.md
phpcs-qa-roadmap.xml
profiles/common/modules/custom/multisite_block_carousel/multisite_block_carousel.module
profiles/common/modules/features/multisite_mediagallery_core/multisite_mediagallery_core.module

NEPT-1484: Execute CS checks earlier in the pipeline
NEPT-1290: Remove check plain on string literals in multisite_block_carousel delete link
NEPT-1286: Removed redeclaration of global variable
- Changed: Pipeline updated to execute CS checks earlier
- Changed: Removed check plain() on link title and replaced with t()
- Fixed: removed redeclaration of global variable

Merge master into release-2.5

---

profiles/common/modules/custom/ecas/ecas_import_users/ecas_import_users.module

Remove the check_plain from the ecas_import_users.
- Removed: Unnecessary check_plain
```sh
no command
```

NEPT-1255: Remove the check_plain from the ecas_import_users.

---

profiles/common/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.install
profiles/common/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.module
tests/features/security/xss_vulnerability.feature

Enforcing the activation of the "Sanitize HTML" filters in all text formats where "Display any HTML as plain text" one is not enabled
- Added: Enforce the activation of the "Sanitize HTML" filters when a text format is saved.
- Added: "hook_updatedb" that enforces the activation of the "Sanitize HTML" filters for already existing formats.
- Changed: Add notification messages in the descriptions of inputs of the "text format" admin interface.
```sh
drush updatedb
```

NEPT-1453: Enforce sanitisation on text formats

---

profiles/common/modules/custom/ecas/includes/ecas.inc

Fix the redirection process that stopped directly after the EU Login process.
- Fixed: Fixed: the redirection definition in the logout call in the ECAS module.
```sh
No command required
```

NEPT-1176: Drupal logout malfunction

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/nexteuropa_laco/src/nexteuropa_laco.behat.inc
profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.module
profiles/common/modules/custom/nexteuropa_varnish/src/Entity/PurgeRule.php
profiles/common/modules/features/multisite_maxlength/src/multisite_maxlength.behat.inc
profiles/common/modules/features/multisite_notifications/multisite_notifications_core/includes/multisite_notifications_core.behat.inc
profiles/common/modules/features/multisite_wysiwyg/multisite_wysiwyg.behat.inc
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/src/tmgmt_poetry.behat.inc
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/tmgmt_poetry_mock/tmgmt_poetry_mock.behat.inc
profiles/common/modules/features/nexteuropa_editorial/src/nexteuropa_editorial.behat.inc
profiles/common/modules/features/nexteuropa_integration/nexteuropa_integration.module
profiles/common/modules/features/nexteuropa_integration/src/ClosureDecoratedMigrateSourceBackend.php
profiles/common/modules/features/nexteuropa_trackedchanges/src/nexteuropa_trackedchanges.behat.inc
tests/features/bootstrap/FeatureContext.php
tests/src/Component/PyStringYamlParser.php
tests/src/Context/ApacheSolrContext.php
tests/src/Context/ContentTypeContext.php
tests/src/Context/DrupalContext.php
tests/src/Context/DrupalMailContext.php
tests/src/Context/FrontendCacheContext.php
tests/src/Context/IntegrationLayerContext.php
tests/src/Context/MessageContext.php
tests/src/Context/MinkContext.php
tests/src/Context/ModuleContext.php
tests/src/Context/MultilingualContext.php
tests/src/Context/PiwikRulesContext.php

Fix QA automation rules be fully namespaced.
ISSUE:
- To follow the QA suggestion rule Drupal.Commenting.DataTypeNamespace.DataTypeNamespace  
we should be removed.
- By running phpcs fire up some errors regarding Coding standard and best practices
- Changed: Remove the rule mention above.
- Fixed: 
Run phpcs and address all outcome issue.
The solution to the most of the issues are the params, vars full namespacing and typo missing
-  Fixed on behat context files.
-  Fixed on common features files.
-  Fixed on common custom modules files.
[No commands]

NEPT-1384 Fix QA automation rules - Data types in @param tags

---

phpcs-qa-roadmap.xml

Fix QA automation rules - Function return type is not void, but function is returning void here
- Removed: The rule ref="Drupal.Commenting.FunctionComment.InvalidReturnNotVoid"
The **phpcs** has not retrieve any error.
NA.

NEPT-1380 Function return type is not void, but function is returning void here

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/nexteuropa_laco/src/nexteuropa_laco.behat.inc
profiles/common/modules/custom/nexteuropa_laco/tests/LanguageCoverageServiceTest.php
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/inc/tmgmt_poetry.webservice.inc
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/tmgmt_poetry_mock/includes/tmgmt_poetry_mock.server.inc
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/tmgmt_poetry_mock/src/Mock/PoetryMock.php
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/tmgmt_poetry_mock/tmgmt_poetry_mock.install
tests/bootstrap.php
tests/src/Context/BeanContext.php

Fix QA automation rules - Namespaced classes/interfaces/traits should be referenced with use statements
- Removed: The rule ref="Drupal.Classes.FullyQualifiedNamespace.UseStatementMissing"
- Fixed: Include the classes by using USE and namespacing
NA.

NEPT-1385 Namespaced classes/interfaces/traits with "use" statements

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/nexteuropa_token/src/HashTokenHandler.php
profiles/common/modules/custom/nexteuropa_token/tests/TokenHandlerAbstractTest.php

Fix QA automation rules - Missing @var tag in member variable comment.
- Changed: Remove exception rule in phpcs-qa-roadmap.xml
- Changed: Update comment lines in profiles/common/modules/custom/nexteuropa_token/ module files.

NEPT-1388: Remove rule and update one line comment style.

---

phpcs-qa-roadmap.xml
profiles/common/modules/features/nexteuropa_trackedchanges/nexteuropa_trackedchanges.helper.inc

Fix QA automation rules - Expected "bool|false" but found "bool|FALSE" for parameter type.
- Changed:
- Exception rule removed in phpcs-qa-roadmap.xml.
- Comment updated.

NEPT-1393: Fix QA automation rules "bool|FALSE .

---

phpcs-qa-roadmap.xml
profiles/common/modules/custom/multisite_config/tests/ConfigBaseTest.php
profiles/common/modules/custom/nexteuropa_token/tests/TokenHandlerTest.php

Fix QA automation rules - Tags should not be used.
- Changed:
Exception removed in phpcs-qa-roadmap.xml
Changes in : profiles/common/modules/custom/nexteuropa_token/tests/TokenHandlerTest.php
profiles/common/modules/custom/multisite_config/tests/ConfigBaseTest.php
1- git fetch --all
2- git checkout nept-884-v2
3- git checkout -b nept-1379

NEPT-1379: Fix QA automation rules - Tags should not be used.

---

phpcs-qa-roadmap.xml
phpcs-ruleset.xml
profiles/common/modules/features/e_library/e_library_core/e_library_core.module
profiles/common/modules/features/events/events_core/events_core.module
profiles/common/modules/features/idea/idea_core/idea_core.module
profiles/common/modules/features/links/links_core/links_core.module
profiles/common/modules/features/multi_user_blog/multi_user_blog.module
profiles/common/modules/features/nexteuropa_geofield/nexteuropa_geofield.module
profiles/common/modules/features/wiki/wiki_core/wiki_core.module

Fix QA automation rules - Line indented incorrectly.
- Removed: The rule ref="Drupal.WhiteSpace.ScopeIndent.IncorrectExact"
- Added: The right indentation.
- Created:  An exception has been set to exclude nexteuropa_newsroom module once it is not 
supported by Core team, so to progress with the clean up for QA AUTOMATION (NEPT-
884, NEPT-1387 and NEPT-1389), this exception must exist so when remove the rule   
"Drupal.Commenting.FunctionComment.ParamMissingDefinition" the phpcs is OK (all 
green).
NA.

NEPT-1390 Fix QA automation rules - Line indented incorrectly

---

phpcs-qa-roadmap.xml
phpcs-ruleset.xml
tests/src/Transformation/Transformer/ArgumentTransformer.php

Fix QA automation rules - Content missing for @var tag in member variable comment.
- Removed: The rule ref="DrupalPractice.General.LanguageNone.Und"
- Added: 
1- An exception has been set to exclude nexteuropa_newsroom module once it is not 
supported   by Core team, so to progress with the clean up for
QA AUTOMATION (NEPT-884, NEPT-1387, NEPT-1389, NEPT-1390, NEPT-1391, NEPT-
1396, NEPT-1400, NEPT-1402, NEPT-1405), this exception must exist while removing the 
rule and get OK from the phpcs (all green).
2- The variable type for heredoc.
NA.

NEPT-1405  Content missing for @var tag 

---

phpcs-qa-roadmap.xml
phpcs-ruleset.xml
profiles/common/modules/custom/nexteuropa_token/modules/nexteuropa_token_ckeditor/views/nexteuropa_token_ckeditor_bean_handler_field_selection.inc
profiles/common/modules/custom/tmgmt_workbench/includes/tmgmt_workbench.plugin.inc

Fix QA automation rules, nused private method.
- Removed: The rule
1- "DrupalPractice.Objects.UnusedPrivateMethod.UnusedMethod"
2- The private methods that are not being used.
- Added: An exception has been set to exclude nexteuropa_newsroom module once it is not 
supported   by Core team, so to progress with the clean up for
QA AUTOMATION (NEPT-884, NEPT-1387, NEPT-1389, NEPT-1390, NEPT-1391, NEPT-1396, 
NEPT-1400), this exception must exist while removing the rule and get OK from the phpcs (all 
green).
NA.

NEPT-1400 Fix QA automation rules - Unused private method.

---

phpcs-qa-roadmap.xml
phpcs-ruleset.xml
profiles/common/modules/custom/multisite_block_carousel/multisite_block_carousel.module
profiles/common/modules/custom/subscriptions_og/subscriptions_og.module
profiles/common/modules/features/cce_basic_config/cce_basic_config.install
profiles/common/modules/features/events/events_core/events_core.module
profiles/common/modules/features/multisite_forum_community/multisite_forum_community.module
profiles/common/modules/features/multisite_mediagallery_core/multisite_mediagallery_core.module
profiles/common/modules/features/news/news_core/news_core.module
profiles/common/modules/features/news/news_og/news_og.module
profiles/common/modules/features/nexteuropa_geofield/nexteuropa_geofield.module
profiles/common/modules/features/nexteuropa_metatags/nexteuropa_metatags.module

Fix QA automation rules,  use LANGUAGE_NONE instead of und.
- Removed: The rule "DrupalPractice.General.LanguageNone.Und"
- Added:  An exception has been set to exclude nexteuropa_newsroom module once it is not supported   by Core team, so to progress with the clean up for
QA AUTOMATION (NEPT-884, NEPT-1387, NEPT-1389, NEPT-1390, NEPT-1391, NEPT-1396, NEPT-1400), this exception must exist while removing the rule and get OK from the phpcs (all green).
- Changed: The 'und' key has been changed by LANGUAGE_NONE const as DRUPAL best practices recommended.
No commands.

NEPT-1402 Use LANGUAGE_NONE instead of 'und'

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.install
profiles/common/modules/features/sitemap/sitemap.strongarm.inc
tests/features/sitemap.feature

Force variable xmlsitemap_prefetch_aliases to 0. This functionality has a very negative impact on performances.
- Changed: value of variable xmlsitemap_prefetch_aliases set to 0.
```sh
drush updb
```

Nept 1584: Force variable xmlsitemap_prefetch_aliases to 0.

---

resources/multisite_drupal_standard.make

Patching iCalcreator library for PHP7 compatibility.
- Added: Patch https://www.drupal.org/files/issues/iCalcreator-php-7-2707373-6.patch for PHP7 compatibility.
```sh
no commands
```

NEPT-263: Adding patch for PHP7 compatibilty to iCalcreator library.

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.install

After a merge ( https://github.com/ec-europa/platform-dev/pull/1714 ) the sequence of hook updates of cce_basic_config is broken.
we have :
219, 220 , 222, 222 , 223 , 224 
It has to be fixed asap.
- Changed:
cce_basic_config.install

NEPT-1630: Reorder hook updates sequence in cce_basic_config.

---

resources/multisite_drupal_standard.make

Upgrade the module to the version 2.0-alpha7.
- Changed: Add a new field to the "password_policy" DB table
```sh
drush updatedb
```

NEPT-364: Upgrade Password Policy to 2.0-alpha7.

---

resources/multisite_drupal_standard.make

Change the way we retrieve file_entity module, to be aligned with QA
- Changed: multisite_drupal_standard.make file, changed to module version + patch instead of commit number

NEPT-1640: Feedback from QA, update file_entity to version + patch.

---

resources/multisite_drupal_standard.make

Update patch to not show the bean h2 when empty.
Quicktab prevent logging missing content
- Changed: Patch on drupal org to hide h2 when title is empty, and patch to not log empty tabs.
```sh
drush cc all
```

NEPT-1038,NEPT-1107 update patch to not show the bean h2 when empty, Quicktab prevent logging missing cont:

---

profiles/common/modules/custom/nexteuropa_varnish/nexteuropa_varnish.module

Nexteuropa varnish, trim base paths from all updated paths
- Fixed: Old paths are not trimmed before being sent to varnish. This follows NEPT-1163.

NEPT-1638: Nexteuropa varnish, trim base paths from all updated paths

---

resources/multisite_drupal_standard.make

Upgrade mpdf to 6.1.4. in order to make the library PHP 7 compliant
- Changed: Upgrade mpdf to 6.1.4.
```sh
drush cc all
```

NEPT-289: Make Mpdf library PHP 7.0 compatibility

---

resources/composer.json
resources/composer.lock

This PR will update Poetry client to version 0.3.5, which contains sanitization fix as per https://github.com/ec-europa/oe-poetry-client/pull/68
- Added: -
- Changed: Update of Poetry client to 0.3.5
- Deprecated: -
- Removed: -
- Fixed: -
- Security: -
Normally it would be enough to run composer install but I'm not sure about which one is the right command in this case since it's very deployment specific.
```sh
$ composer install
```

NEPT-1701: [Poetry client] Sanitization of text fields on support-2.3

---

resources/composer.json
resources/composer.lock

This PR will update Poetry client to version 0.3.5, which contains sanitisation fix as per https://github.com/ec-europa/oe-poetry-client/pull/68
- Added: -
- Changed: Update of Poetry client to 0.3.5
- Deprecated: -
- Removed: -
- Fixed: -
- Security: -
As the release package already have embed libraries there is no need to run any additional command.

NEPT-1701: [Poetry client] Sanitisation of text fields

---

resources/multisite_drupal_standard.make

The folder graph_cache is empty on the downloaded archive, we change the library mpdf source in make file.
- Changed:
resources/multisite_drupal_standard.make

NEPT-1159: Update mpdf library source in make file.

---

resources/multisite_drupal_standard.make

Upgrade metatag module version 1.21 to 1.22
- Changed:
Version 1.21 to 1.22
- Removed:
Patch that is not needed [anymore](https://www.drupal.org/files/issues/undefined_group_in_i18n-2882048-5.patch)

NEPT-1323 Upgrade metatag module version 1.21 to 1.22

---

profiles/common/modules/custom/multisite_drupal_language_negociation/multisite_drupal_language_negociation.module

Fix issue with the misuse of LANGUAGE_NONE in the multisite_drupal_language_negociation_views_query_alter
- Fixed: misuse of LANGUAGE_NONE in the multisite_drupal_language_negociation_views_query_alter

NEPT-1753: Concatatenate the LANGUAGE_NONE instead of put between doubble quotes

---

resources/multisite_drupal_standard.make

Clone is a reserved keyword since PHP5. Patch date_ical
- Added: Patch on date_ical

NEPT-266: Add a patch to resolve PHP7 issue.

---

resources/multisite_drupal_standard.make

Hide the label of the europasearch form by default
- Changed: ec_resp version

NEPT-1756: Hide the label of the europasearch form by default

---

resources/multisite_drupal_standard.make

Upgrade rules module to version 2.10
- Changed: Version of rules module.
```sh
drush updb
```

NEPT-1325: Upgrade rules module to version 2.10

---

phpcs-ruleset.xml

In some cases, it is impossible to push commit to github because the phpcs step raises errors on the "nexteuropa_newsroom" module.
That should never happen because "nexteuropa_newsroom" module is en external module that is not maintained by the platform team and does not belong to the project github repository.
The phpcs rules must be updated to exclude the module from the CS process.
- Changed: /phpcs-ruleset.xml

Add newsroom to phpcs exclusion

---

profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_poetry/plugins/tmgmt_poetry.plugin.inc

Add condition on the current year into the "max" queries used in the poetry ref. generation.
- Added: The generateRequestId method of TMGMTPoetryTranslatorPluginController

NEPT-1823: Fix the incorrect Poetry reference numbering

---

resources/multisite_drupal_standard.make

Upgrade FileField source to the latest version
- Changed: multisite_drupal_standard.make
drush cc all

NEPT-1824: Upgrade filefield_sources to 11.

---

resources/drupal-core.make

nept-1849: Update drupal core to 7.57

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.helpers.inc
profiles/common/modules/features/cce_basic_config/cce_basic_config.module

In order to prevent insertion of emoji characters in database, we added validation on text-fields, body-texts and subject and titles
- Changed:
profiles/common/modules/features/cce_basic_config/cce_basic_config.module
profiles/common/modules/features/cce_basic_config/cce_basic_config.helpers.inc

NEPT-1679: Add custom validation for emoji (#1884)

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.helpers.inc
profiles/common/modules/features/cce_basic_config/cce_basic_config.module
resources/multisite_drupal_standard.make

Updated entitycache module to 1.5. Additional hook_entitycache_node_load to mitigate https://www.drupal.org/project/entitycache/issues/2877280
drush updb entitycache
drush registry-rebuild ( https://www.drupal.org/project/entitycache/releases/7.x-1.5)

Upgrade entitycache to 7.x-1.5

---

profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/includes/forms/tmgmt_dgt_connector_form_cart_bundle_items.inc
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/includes/views/tmgmt_dgt_connector_cart.views_default.inc
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/src/ViewsHandler/CartBundleActionsField.php
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/tmgmt_dgt_connector_cart.module
profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.views_default.inc
tests/behat.yml.dist
tests/features/tmgmt/tmgmt_dgt_connector_cart.feature

Add link Small Jobs, to DGT Cart page, in TMGMT page and menu.
- Added: Small Jobs link to DGT cart.
- Changed: Cart Bundle URL (from admin/dgt_connector/cart to admin/tmgmt/dgt_cart).
- Changed: Message after adding to the cart as now link to cart page.
No commands needed.

NEPT-1080: Add link to DGT cart

---

profiles/common/modules/features/nexteuropa_geofield/nexteuropa_geofield.info
profiles/common/modules/features/nexteuropa_geofield/nexteuropa_geofield.module

Limit the use of HTML tags to inline one in the nexteuropa_geofield fields.
- Changed: Add filter to limit the HTML tags uses in nexteuropa_geofield fields.
drush cc all

NEPT-1879: Improve the control on the pop-up display limitations.

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.helpers.inc
profiles/common/modules/features/multisite_settings/multisite_settings_core/multisite_settings_core.install

Enforce the activation of the "Administration language negotiation" module on all sites that do not have enable its alternative "Administration language".
- Added: "multisite_settings_core_update_7124" hook.
drush updatedb

NEPT-1871: Add hook_update for enforcing the administration_language_negotiation

---

resources/multisite_drupal_standard.make

Upgrade message to 1.12 and add the necessary patches.
- Changed: resources/multisite_drupal_standard.make to upgrade the message module
- Changed: resources/multisite_drupal_standard.make to take into account of 2 patches for the message module.
drush updatedb

NEPT-1744: Upgrade message to 1.12 and add the necessary patches.

---

profiles/common/modules/custom/nexteuropa_json_field/nexteuropa_json_field.module
profiles/common/modules/features/nexteuropa_webtools/nexteuropa_webtools.admin.inc
profiles/common/modules/features/nexteuropa_webtools/nexteuropa_webtools.features.field_instance.inc

Add the "defer" attribute on the script HTMl tag generated by nexteuropa_json_field
- Added: The field setting parameter "defer_on_js_to_load" for "JSON settings" fields
- Changed: Set the "field_json_object" field of the web tools block type to take into account of "defer_on_js_to_load"     
drush cc all

NEPT-1894: Add "defer_on_js_to_load" paremeter and the "defer" attribute in nexteuropa_json_field

---

resources/drupal-core.make

Update Drupal core to 7.58
* Security: Update Drupal core to 7.58
No command.

NEPT-1890: Update Drupal core to 7.58

---

resources/multisite_drupal_standard.make

Use the release 0.1.0 of nexteuropa_poetry instead of the master branch.
- Changed: nexteuropa_poetry declaration in the resources/multisite_drupal_standard.make
No command

NEPT-1902: Use the release 0.1.0 of nexteuropa_poetry

---

profiles/common/modules/features/multisite_wysiwyg/multisite_wysiwyg.behat.inc

NEPT-1741: Duplicate temporaly getTableRow to unblock the toolkit build process.
- Changed: Add getTableRow  method into multisite_wysiwyg.behat.inc
None

NEPT-1741: Duplicate temporaly getTableRow to unblock the toolkit build process

---

resources/multisite_drupal_standard.make

Upgrade ec_resp to latest release.
- Changed: resources/multisite_drupal_standard.make to change the ec_resp release number
drush cc all

NEPT-1828: Upgrade the ec_resp release version

---

resources/multisite_drupal_standard.make

* NEPT-1828: Upgrade temporarily the ec_resp release version for the nept-1828 branch.
* NEPT-1828: Upgrade ec_resp to 2.3.7.
Upgrade ec_resp to latest release.
- Changed: resources/multisite_drupal_standard.make to change the ec_resp release number
drush cc all

NEPT-1828: Upgrade the ec_resp release version (#1978)

---

profiles/common/modules/features/nexteuropa_mediagallery/nexteuropa_mediagallery.info

Fix nexteuropa_multimedia package name
- Changed: Change package name to NextEuropa

NEPT-1441: CLONE - [nexteuropa_mediagallery] minimal typo in package name at .info file

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.install
profiles/common/modules/features/nexteuropa_mediagallery/nexteuropa_mediagallery.info
profiles/common/modules/features/nexteuropa_trackedchanges/nexteuropa_trackedchanges.module
profiles/multisite_drupal_communities/modules/custom/multisite_dynamic_basetheme
profiles/multisite_drupal_standard/modules/custom/multisite_dynamic_basetheme
resources/multisite_drupal_standard.make

NEPT-1828: Upgrade the ec_resp release version (#1978)
NEPT-1441: Use correct package name NextEuropa (#1975)
NEPT-1923: Upgrade ds to 2.15. (#2008)
NEPT-1593: Add ckeditor to filtered format. (#1992)
NEPT-1931: Remove useless symlinks. (#2016)
NEPT-1909: Update Atomium version from 2.7 to 2.8. (#1988)
drush cc all

Release 2.5 merge into Release 2.6

---

resources/drupal-core.make

Update Drupal core to 7.59
- Security: Update Drupal core to 7.59
No command.

NEPT-1932: Update drupal core version to 7.59.

---

resources/drupal-core.make

Update Drupal core to 7.59
- Security: Update Drupal core to 7.59
No command.

NEPT-1932: Update Drupal core to 7.59

---

profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector.inc
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector.install
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector.module
tests/features/tmgmt/tmgmt_dgt_connector_cart.feature

Ensure beans can be send to DGT using Smalljobs.
- Added: Test for blocks translation
- Added: Blocks activation in entity translation configuration, when enabling module "TMGMT DGT connector"
- Changed: Blocks translation form to use default plugin
No commands are needed.

NEPT-1860 - [Small jobs] Ensure beans can be send to DGT

---

profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/README.md
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/tmgmt_dgt_connector_cart.module

Remove the default TMGMT Cart
- Removed: original cart.
- Reworked: Readme.
- Changed: Make Readme file more understandable.
- Changed: Add small clarification for beans.
- Changed: Add unsuported string types.
drush cc all

Nept-1882: Remove the default TMGMT Cart

---

profiles/common/modules/custom/tmgmt_og/README.txt
profiles/common/modules/custom/tmgmt_workbench/tmgmt_workbench.info
profiles/common/modules/features/nexteuropa_editorial/nexteuropa_editorial.install
resources/multisite_drupal_standard.make

Upgrade ec_resp to the version containing the fix for the caption display of views table template.
- Changed: Modify the ec_resp version into multisite_drupal_standard.make
drush cc all

NEPT-1951: Prepare the ec_resp release with the views table fix for the caption

---

resources/multisite_drupal_standard.make

Set nexteuropa_newsroom version to v3.5.2 for the platform
- Changed: nexteuropa_newsroom reference in the multisite_drupal_standard.make
No command

NEPT-1928: Point the make file to the release v3.5.2 of nexteuropa_newsroom

---

profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/tmgmt_dgt_connector_cart.module
profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.callbacks.inc
resources/multisite_drupal_standard.make

- Fix the ec_resp declaration into the multisite_drupal_standard.make to point correctly to the tag 2.3.9;
- Add the "t" function for the TMGT "Add to cart" feature in tmgmt_dgt_connector_cart module;
- Fix the "Call to undefined function drupal_lookup_path()" detected during the QA review.
- Added: "t" function in _tmgmt_dgt_connector_cart_sources_add_cart_button().
- Changed: The ec_resp declaration in multisite_drupal_standard.make
- Fixed: Call to undefined function drupal_lookup_path() issue in nexteuropa_multilingual.callbacks.inc
- Security:

NEPT-1974: Fixes required by QA about 2.5.36

---

profiles/common/modules/features/multisite_multilingual_references/multisite_multilingual_references.module

Add _multisite_multilingual_references_add_widget_in_html() and _multisite_multilingual_references_get_widget_from_entityreference() and fix the fatal error coming from the node "content" property that are objects while arrays are expected.
- Changed: multisite_multilingual_references_entity_view() in profiles/common/modules/features/multisite_multilingual_references/multisite_multilingual_references.module
No command is needed

NEPT-1175: Add _multisite_multilingual_references_add_widget_in_html() and ..._get_widget_from_entityreference().

---

resources/multisite_drupal_standard.make
tests/features/content_accessibility.feature
tests/features/editorial_workflow.feature
tests/src/Context/DrupalContext.php

Remove workbench_og-my_drafts_missing-2006134-4.patch that is problematic for the access to unpublished content.
Add basic Behat tests to check the accessibility to unpublished contents by the default user roles.
- Added: tests/features/content_accessibility.feature.
- Changed: resources/multisite_drupal_standard.make to remove the patch.
No command

NEPT-1986: Remove workbench_og-my_drafts_missing-2006134-4.patch

---

Jenkinsfile

Use a static workspace path for all nodes, to avoid random failures
- Changed: Pipeline workspace path for all nodes is now static
No command

NEPT-1979: Force static build workspace to avoid random failures

---

profiles/common/modules/custom/nexteuropa_piwik/nexteuropa_piwik.module
profiles/common/modules/features/multisite_multilingual_references/multisite_multilingual_references.module
profiles/common/modules/features/multisite_wysiwyg/multisite_wysiwyg.module
profiles/common/modules/features/nexteuropa_dgt_connector/tmgmt_dgt_connector/tmgmt_dgt_connector_cart/tmgmt_dgt_connector_cart.module
profiles/common/modules/features/nexteuropa_geofield/js/nexteuropa_geofield.edit.js
profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.callbacks.inc
resources/multisite_drupal_standard.make
tests/features/content_accessibility.feature
tests/features/editorial_workflow.feature
tests/src/Context/DrupalContext.php

- Fix the ec_resp declaration into the multisite_drupal_standard.make to point correctly to the tag 2.3.9;
- Add the t function for the TMGT "Add to cart" feature in tmgmt_dgt_connector_cart module;
- Fix the Call to undefined function drupal_lookup_path() detected during the QA review.
- Added: t function in _tmgmt_dgt_connector_cart_sources_add_cart_button().
- Changed: The ec_resp declaration in multisite_drupal_standard.make
- Fixed: Call to undefined function drupal_lookup_path() issue in nexteuropa_multilingual.callbacks.inc
- Security:

NEPT-1974: Fixes required by QA about 2.5.36 (#2079)

---

resources/multisite_drupal_standard.make

Add patch of D.o issue 2082573 related to I18n module ini order to fix the fatal error "call to undefined method".
This fatal error occurs on some sub-sites when they install/enable a new module on their site.
The patch fixes the issue by resetting the static caches used by I18n module. 
- Changed: multisite_drupal_standard.make, add the line declaring the 2082573 patch
No drush command

NEPT-1987: Fix in i18n Fatal Error Call to undefined method i18n_object_wrapper::strings_update()

---

profiles/common/modules/custom/nexteuropa_token/modules/nexteuropa_token_ckeditor/plugins/nexteuropa_token_ckeditor/plugin.js
profiles/common/modules/custom/nexteuropa_token/src/Entity/LinkTokenHandler.php

- Strip the hyperlink generated for an internal link (nexteuropa_token) in order to ensure that unwanted line break or empty space are displayed with link. 
- Improve the management of the nexteuropatoken tag insertions in the WYSIWYG content when the contribution is done in Firefox or I.E..
These browsers managed badly the space when they process ckeditor content. The new implementation take into account as much as possible of this limitation.
- Changed: nexteuropa_token/src/Entity/LinkTokenHandler.php: Trim on the replacement link in the method hookTokens()
- Changed: nexteuropa_token_ckeditor/plugin.js: Add the process controlling the space around nexteuropatoken tags.
drush cc all
The contributor should be notified they need to clean the cache of their browser.

NEPT-1989: Fix the display of internal links using the link theme and contributed in FF or IE.

---

resources/multisite_drupal_standard.make

When handling big amount of nodes or redirections it is possible to duplicate hashes which leads to database exceptions. 
- Fixed: Prevent duplicate hashes causing database exceptions.

NEPT-1946: Prevent duplicate hashes causing database exceptions.

---

resources/multisite_drupal_standard.make
resources/patches/redirect-duplicate_redirect_save_handling-2260499-nept-1946.patch

Add Redirect module to the platform stack. 
The chosen version included extra commits compared to the current official version 7.x-1.0-rc3:
- Issue #2574593: Fixed watchdog variables in redirect_change_status_multiple();
- Issue #2541304: Fixed errors in cases where redirect_update_7101() needs to run more than once;
- Issue #1961530: Added a limit to how many redirects are purged for each cron run.
- Issue #1768530: Integrate the redirect textfield with the Menu Path Autocomplete (mpac) module if it is available;
Some non committed patches have been also added:
- Issue #2057615: Increase size of source field to hold long URLs;
- Issue #2260499: Generate redirects (Duplicate entry for key hash);
- Issue #1396446: Redirects deleted too early (New redirects being deleted by cron)
The module …

NEPT-1915: Add Redirect module to the platform stack

---

profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.module
resources/drupal-core.make

Keep previous alias when using option "Create a new alias. Leave the existing alias functioning. " on URL aliases configuration.
- Changed: function _nexteuropa_multilingual_path_und_sync() to handle all url configuration options.

NEPT-1993: Backport changes to alias creation from 2.5 version

---

profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.module
resources/drupal-core.make
resources/multisite_drupal_standard.make

- Fixing issue with the class loading during the registry rebuild.
- Keep previous alias when using option Create a new alias. Leave the existing alias functioning. on URL aliases configuration.
- Changed: Add registry_autoload 2870868 patch to  multisite_drupal_standard.make
- Changed: function _nexteuropa_multilingual_path_und_sync() to handle all url configuration options.
drush cc all

NEPT-1950, NEPT-1993: Merge from release-2.5 to release-2.6

---

resources/multisite_drupal_standard.make

Add feeds_et module in the platform stack as it is a dependency for nexteuropa_newsroom project.
The inclusion follows the guidelines given by nexteuropa_newsroom to subsites; I.E.:
- commit: bf0d6d00b1a80a630d4266b04c254f2335177346
- patch: feeds_et_link_support-2078069-3.patch
- Changed: multisite_drupal_standard.make to add the feeds_et module declaration with the required patch.
No command required.

NEPT-2018: Add feeds_et module in the platform stack

---

resources/multisite_drupal_standard.make

Remove fblikebutton module from the platform stack.
- Changed: multisite_drupal_standard.make remove the module reference.
No command needed.

NEPT-1567: Remove fblikebutton module from the platform stack

---

resources/multisite_drupal_standard.make

Add feeds_et module in the platform stack as it is a dependency for nexteuropa_newsroom project.
The inclusion follows the guidelines given by nexteuropa_newsroom to subsites; I.E.:
- commit: bf0d6d00b1a80a630d4266b04c254f2335177346
- patch: feeds_et_link_support-2078069-3.patch
- Changed: multisite_drupal_standard.make to add the feeds_et module declaration with the required patch.
No command required.

NEPT-2018: Merge into 2.6: Add feeds_et module in the platform stack

---

resources/multisite_drupal_standard.make

Upgrade Rules to 2.11.
- Changed: resources/multisite_drupal_standard.make
- Ste the module version to 2.11
- Remove the obsolete patch rules_init_and_cache-2851567-8.patch
drush cc all

NEPT-2010: Upgrade Rules to 2.11

---

profiles/common/modules/features/ec_embedded_video/ec_embedded_video.install.inc

Securing the _ec_embedded_video_install_soft_configured_file_display function in order to avoid create a file display config. that exist already in the site.
- Changed: _ec_embedded_video_install_soft_configured_file_display(), add test based on the already saved file display.
No command

NEPT-2022: Check the ec_embedded_video file displays exist bfore creating them

---

build.properties.dist
profiles/common/modules/custom/ecas/includes/ecas.inc
profiles/common/modules/features/ec_embedded_video/ec_embedded_video.install.inc
profiles/common/modules/features/ecas_env/ecas_env.module
resources/multisite_drupal_standard.make
tests/behat.yml.dist

- NEPT-1997: Avoid PHP error/notices in ecas
- NEPT-858: Restore browser parameters
- NEPT-2033: Upgrade Select (or other) module to 2.24
- NEPT-2002: XML Sitemap reflecting wrong publication status
- NEPT-2010: Upgrade Rules to 2.11
- NEPT-2022: Check the ec_embedded_video file displays exist before creating them
- NEPT-1866: Contributor to see own drafts under Manage Content/My drafts workbench tab
- Added: Patch for workbench_og: workbench_og-my_drafts_missing-2006134-6.patch
- Changed: function normal_menu_logout_check()
- Changed: function ecas_menu_logout_check()
- Changed:  behat.yml.dist and build.properties.dist
- Changed: resources/multisite_drupal_standard.make, upgrade the module version.
- Changed: resources/multisite_drupal_standard.make, change the version of the xmlsitemap …

 NEPT-1997: Merge from release-2.5 to release-2.6

---

resources/multisite_drupal_standard.make

- Upgrade migrate to 2.11 
- Adding the patch fixing the Migration::applyMappings() problem with handle multifield subfields (https://www.drupal.org/project/migrate/issues/2588341)
- Added:
- Changed: resources/multisite_drupal_standard.make to replace:
- The migrate version declaration to 2.11
- Add the 2018-06-25/2588341-9.patch patch 
No command needed.

NEPT-2000: Upgrade migrate to 7.x-2.11

---

resources/multisite_drupal_standard.make

It happens with some site configuration that PHP notices are logged .
The facetapi-2768779-facetapi_map_assoc-undefined-index.patch is fixing this.
- Changed: resources/multisite_drupal_standard.make to add the patch reference.
None

NEPT-2042: Add facetapi patch to fix the Undefined index: field api bundles notice

---

resources/drupal-core.make
resources/patches/set-session-cookie-lifetime-0.patch

By default, Drupal ships with a session expiration time of just over 23 days, using this directive in settings.php:
ini_set('session.cookie_lifetime', 2000000);
We decrease the number to 0 in order to delete cookies as soon as the browser is closed.
- Changed: Decreased session.cookie_lifetime variable.

NEPT-900: Decrease current session timeout

---

profiles/common/modules/features/nexteuropa_europa_search/nexteuropa_europa_search.module

The Europa Search service URL that issued by the nexteuropa_europa_search module, has changed.
The default URL value set in the module has been changed to point to the new URL.
- Changed: nexteuropa_europa_search.module, the default value of the nexteuropa_europa_search_url variable 
drush cc all

NEPT-2036: Change the default value for the Europa Search service URL

---

profiles/common/modules/features/nexteuropa_europa_search/nexteuropa_europa_search.module
resources/drupal-core.make
resources/patches/set-session-cookie-lifetime-0.patch

By default, Drupal ships with a session expiration time of just over 23 days, using this directive in settings.php:
ini_set('session.cookie_lifetime', 2000000);
We decrease the number to 0 in order to delete cookies as soon as the browser is closed.
The Europa Search service URL that issued by the nexteuropa_europa_search module, has changed.
The default URL value set in the module has been changed to point to the new URL.
- Changed: nexteuropa_europa_search.module, the default value of the nexteuropa_europa_search_url variable 
- Changed: Decreased session.cookie_lifetime variable.
drush cc all

NEPT-900/2036: Merge from 2.5 to 2.6

---

profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/TMGMTDefaultTranslatorPluginController/TmgmtDgtFttTranslatorPluginController.php
profiles/common/modules/features/nexteuropa_dgt_connector/ne_tmgmt_dgt_ftt_translator/src/Tools/DataProcessor.php
resources/composer.json
resources/composer.lock
tests/features/tmgmt/fast-track.feature
tests/features/tmgmt/fast-track_custom-delay.feature

Update fast track translation to use the product identifier 'EDT' rather than 'REV'.
- Added: Custom product identifier within the review request method to pass 'EDT'.
- Changed: oe-poetry-client to version 0.3.6 which supports custom product identifier's. Additional test coverage of the product identifier within the fast track tests.
Not applicable.

NEPT-2047: Fasttrack, use the product identifier 'EDT' rather than 'REV'

---

profiles/common/modules/custom/ecas/includes/ecas.inc

Cast as array the cas:group parameter in the ecas_ecas_sync_user_info() in order to ensure we treat an array in the CEM role assignment process.
- Changed: profiles/common/modules/custom/ecas/includes/ecas.inc: cast cas:groups/cas:group as array in ecas_ecas_sync_user_info().

NEPT-2058: Cast $user_info[cas:groups][cas:group] based on the EAC-EYP patch

---

profiles/common/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.sanitize.inc

Fix the sanitise HTML filter that breaks url token href attributes. 
- Changed: sanitise HTML filter that removed some URL token from href attributes.
Not applicable.

NEPT-2067: href token replacement

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.info
profiles/common/modules/features/multisite_wysiwyg/multisite_wysiwyg.info

media_wysywig_view_mode is deprecated. Remove from the platform
- Removed: dependencies to the module in the info files

NEPT-1615: Remove dependencies to the outdated module from the platform

---

profiles/common/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.sanitize.inc
profiles/common/modules/custom/nexteuropa_token/modules/nexteuropa_token_ckeditor/plugins/nexteuropa_token_ckeditor/plugin.js
profiles/common/modules/features/cce_basic_config/cce_basic_config.info
profiles/common/modules/features/multisite_wysiwyg/multisite_wysiwyg.info
resources/multisite_drupal_standard.make

- NEPT-1615: Remove dependencies to the outdated module from the platform
- NEPT-2052: Add plupload patch to allow sub directories with S3
- NEPT-2057: Ensure that nexteuropa_token plugin respects the source formatting rules.
- NEPT-2067: Fix the sanitise HTML filter that breaks url token href attributes.
- Added: Patch (#2974466) to plupload module.
- Changed:
- Replaced the use of htmlParser.basicWriter method with the correct CKEDITOR.htmlWriter method that respects the formatting configuration.
- Sanitise HTML filter that removed some URL token from href attributes.
- Removed: dependencies to the module in the info files
Not applicable

NEPT-1615, NEPT-2052, NEPT-2057, NEPT-2067: Merge from 2.5 into 2.6 

---

profiles/common/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.sanitize.inc

Add the ability to use the mailto, tel protocols within anchor href attributes.
- Changed: Sanitise HTML filter, to allow the mailto, and tel protocols. These are allowed by default in core.
Not applicable.

NEPT-2076: anchor href allowed protocols

---

profiles/common/modules/features/cce_basic_config/cce_basic_config.install

multisite_version variable is no longer used in 2.5, we remove it from the db.
- Removed: multisite_version variable
`drush updb`

NEPT-2065: remove variable that is no longer used.

---

profiles/common/modules/custom/multisite_drupal_toolbox/multisite_drupal_toolbox.sanitize.inc
profiles/common/modules/features/cce_basic_config/cce_basic_config.info
profiles/common/modules/features/cce_basic_config/cce_basic_config.install
profiles/common/modules/features/cce_basic_config/cce_basic_config.strongarm.inc
tests/features/status_page.feature

-  NEPT-2065: Fix the display of version tag and commit id. Add the timestamp information.
- NEPT-2076: Add the ability to use the mailto, tel protocols within anchor href attributes.
- Added: Timestamp information in the status report in the UI.
- Changed: 
- Point the Tag and Commit information to the files generated by fpfis-scheduler during the deployment process.
- Sanitise HTML filter, to allow the mailto, and tel protocols. These are allowed by default in core.
- Deprecated: variable multisite_version will be uninstalled from 2.6
- Removed: variable multisite_version is still present but no longer displayed in UI
- Security:
Not applicable.

 NEPT-2065, NEPT-2076: Merge from 2.5 to 2.6

---

profiles/common/modules/features/multisite_settings/multisite_settings_core/multisite_settings_core.install

The language configuration should be set for language url_suffix by default, however, this is not the case on 2.3 so while updating to 2.5 the config is not set as expected.
- Fixed:
To fix the issue a sniped code has been added to the update hook, which will fix the issue when any subsite update to 2.5.
`drush updb`

NEPT-2074: Set language url_suffix as default behaviour while updating to 2.5

---

resources/multisite_drupal_standard.make

Upgrade views to 3.20
- Changed: resources/multisite_drupal_standard.make
- Update Views version
- Remove views-and_missing_parenthesis-2908538-2-D7.patch: Put extras in parentheses, otherwise OR conditions...
- Add views-check-exposed-identifier.patch: Undefined index: status in views_handler_filter->store_exposed_input()
drush cc all

NEPT-2011: Upgrade Views to 3.20

---

resources/drupal-core.make

Implement in the _filter_url() function, urt pattern search with unicode and a fallback to hexadecimal values in there is no unicode support
- Added: patch https://www.drupal.org/files/issues/2018-09-28/filter-urlfilter-i18n-1657886-40.patch

NEPT-1995: CLONE - INFO - URL with brackets gets incorrectly linked

---

profiles/common/modules/features/ec_embedded_video/ec_embedded_video.module
profiles/common/modules/features/ec_embedded_video/themes/media-avportal-video.tpl.php
resources/drupal-core.make
resources/multisite_drupal_standard.make

- NEPT-1995: Implement in the _filter_url() function, urt pattern search with unicode and a fallback to hexadecimal values in there is no unicode support.
- NEPT-1198: Upgrade the media_avportal module to 1.3 in order to take the new service into account.
- Added: patch https://www.drupal.org/files/issues/2018-09-28/filter-urlfilter-i18n-1657886-41.patch
- Changed: resources/multisite_drupal_standard.make, upgrade media_avportal to 1.3
drush cc all

NEPT-1995, NEPT-1198: Merge from 2.5 into 2.6

---

resources/multisite_drupal_standard.make

Fix the fatal error 
Argument 1 passed to xmlsitemap_node_create_link() must be an instance of stdClass, boolean given, called in .../xmlsitemap/xmlsitemap_node/xmlsitemap_node.module
on line 28 and defined xmlsitemap_node.module:194
- Changed: resources/multisite_drupal_standard.make, add xmlsitemap-2986847-2.patch reference

NEPT-2082: Add 2986847 patch for fixing the issue with  xmlsitemap_node_create_link() during cron running

---

resources/multisite_drupal_standard.make

Upgrade print to 2.2.
- Changed: resources/multisite_drupal_standard.make to upgrade the print module version.
drush cc all

NEPT-2093: Upgrade print to 2.2

---

resources/multisite_drupal_standard.make

Unknown or bad timezone 
- Added: Patch on rate_expiration d.o issue 1421016

NEPT-2095: Don't use an empty timezonestamp.

---

resources/drupal-core.make

Update Drupal Core to 7.60.
- Changed: resources/drupal-core.make: Change the Drupal Core version.
No command to execute.

NEPT-2106: Update Drupal Core to 7.60

---

profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.module
resources/drupal-core.make

* NEPT-794: Remove unwanted html tags in nexteuropa multilingual warning message.
* NEPT-794: Add filter_xss.
* NEPT-794: Add array allow_tags.
- Changed: profiles/common/modules/features/nexteuropa_multilingual/nexteuropa_multilingual.module
No commands needed

NEPT-794: Customizable message in workbench moderation is broken (#2209)
